### ISSUE TITLE
Error comparing filter values

### ISSUE THREAD

**Issue by xlancer** [dotliquid/dotliquid#102]
I try to compare value produced by filter |size using < and > operators and it doesn't work. The result is always TRUE. Operator == works correctly. It seems that this values are compared as strings.

Sample:
  {% if collection | size < 2 %}
    less or equal 1
  {% else %}
    greater than 1
  {% endif %}

Result:
"less or equal 1" regardless of the input collection size

**Comment by mikebridge** [comment]
According to https://github.com/Shopify/liquid/issues/362#issuecomment-44844944, the original shopify version of Liquid doesn't support filters in conditionals either. You can use an "assign" tag though.
