### ISSUE TITLE
Standard filters missing?

### ISSUE THREAD

**Issue by Piedone** [dotliquid/dotliquid#103]
Trying to render the introductory sample from the Liquid docs doesn't yield expected results. Rendering the following:

```
Hello {{ 'tobi' | upcase }}
Hello tobi has {{ 'tobi' | size }} letters!
Hello {{ '*tobi*' | textilize | upcase }}
Hello {{ 'now' | date: "%Y %h" }}
```

results in the following output:

```
Hello tobi Hello tobi has tobi letters! Hello *tobi* Hello now
```

None of the filters seem to actually modify the string. Is there any preliminary setup needed or are these filters not supported OOTB?

**Comment by jindovu** [comment]
Hello everyone,
       Now .NET upgrade .NET Core RC2 run on Linux, Window OS, I build a system using dotLiquid to generate template site, please let me know how can I integration between dotLiquid and .NET Core RC2

Thank you so much.
