### ISSUE TITLE
Liquid Error - 'extends' must be the first tag in an extending template

### ISSUE THREAD

**Issue by Terry1511512** [dotliquid/dotliquid#105]
I have a very basic template ie:

    {% extends "Body.tpl" %}

    {% block content %} 
        <p>
            <a href="{{Url}}">{{Title}}</a>
        </p>
    {% endblock %}
The Body.tpl is a lot more complicated but basically has the two sections:

    <title>{% block title %}Default Title{% endblock %}</title>
    <div id="div1" class="fluid">{% block content %}No Content{% endblock %}</div>

and the C# code is:

    public static class DotLiquidTemplate
    {
        public static Template Parse( string Html )
        {
             Template.NamingConvention = new DotLiquid.NamingConventions.CSharpNamingConvention();
             Template.FileSystem = new LocalFileSystem( Globals.AbsolutePath + @"\Html\" );
             return Template.Parse( Html );
        }
    }

But when I try to parse the template I get the error:

     Liquid Error - 'extends' must be the first tag in an extending template

But a far as I can see 'extends' <b>is</b> the first tag in the template.

Any help much appreciated.

Thanks in advance
Terry

**Comment by haf** [comment]
Hi Terry. That token is called the byte-order-mark. It is a Windows-ism. Your file reader should be able to handle it. PRs welcome.
