### ISSUE TITLE
Support for cultures with "," as the decimal separator is broken

### ISSUE THREAD

**Issue by sbertho** [dotliquid/dotliquid#106]
Hi,

In Context.cs:
<pre>
if (match.Success)
			{
				// For cultures with "," as the decimal separator, allow
				// both "," and "." to be used as the separator.
				// First try to parse using current culture.
				float result;
				if (float.TryParse(match.Groups[1].Value, out result))
					return result;

				// If that fails, try to parse using invariant culture.
				return float.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
			}
</pre>

is broken.
CultureInfo.NumberFormat.NumberGroupSeparator = "."
CultureInfo.NumberFormat.NumberDecimalSeparator = ","

Then .NET will parse "1.2" to 12, because .NET first removes all NumberGroupSeparator from the string.

A working solution would be:
<pre>
if (match.Success)
            {
                var value = match.Groups[1].Value;
                // For cultures with "," as the decimal separator, allow
                // both "," and "." to be used as the separator.
                value = Regex.Replace(value, @"[\.]", CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator);

                return float.Parse(value, CultureInfo.CurrentCulture);
            }
</pre>

**Comment by haf** [comment]
@sbertho Do you think you could PR this? Thanks
