### ISSUE TITLE
LiquidType attribute and inheritance

### ISSUE THREAD

**Issue by fsw** [dotliquid/dotliquid#113]
Please consider following code:
```csharp
[LiquidType("Weight")]
public class Fruit
{
        public float Weight { get; set; }
}

[LiquidType("Curvative", "Weight")]
public class Banana : Fruit
{
        public float Curvative { get; set; }
}
```
at the moment I would have to explicitly specify all parent fields like "Weight" in derived classes to be available from templates.
Wouldn't it be better if inheritance was applied to allowedMembers list?
Wouldn't it be even better to have a LiquidProperty attribute?
So above code might look like:

```csharp
[LiquidType]
public class Fruit
{
        [LiquidProperty]
        public float Weight { get; set; }
}

[LiquidType]
public class Banana : Fruit
{
        [LiquidProperty]
        public float Curvative { get; set; }
}
```
This will allow to "disable" a property in child classes if required.
Please let me know if this is desirable and I will work on a pull request.

cheers

**Comment by haf** [comment]
@fsw Do you think you could PR your simple version?

**Comment by fsw** [comment]
Sorry @haf I am not using dotliquid any more so I have no resources and I wont feel enough competent to PR this quick draft.
However if you or anyone would see this change useful, please feel free to use this commit as a starting point and just check if it wont be a performance bottleneck for rendering.
I am really happy seeing this cool project getting alive again though.
