### ISSUE TITLE
Make it simpler to use DTO classes to fill DotLiquid templates

### ISSUE THREAD

**Issue by marc-at-nowhow** [dotliquid/dotliquid#117]
I am trying to use DotLiquid with my own DTO classes to get my data into a DotLiquid template.

This notation "works" - but it seems a bit overly complicated..... why do I have to specify each and every single property?? 

    [LiquidType("Birthday", "Email", "Name", "Phone")]
    public class MyDto
    {
        public string Name { get; set; }
        public string Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }

Couldn't we just use **all** public properties?

Or alternatively, how about being able to decorate those properties I want to use for template binding with a [LiquidMember] attribute (like the [DataMember] in WCF data contracts):

    [LiquidType]
    public class MyDto2
    {
        [LiquidMember]
        public string Name { get; set; }

        [LiquidMember(FormatString = "dd.MM.yyyy")]
        public DateTime Birthday { get; set; }

        [LiquidMember]
        public string Email { get; set; }

        [LiquidMember]
        public string Phone { get; set; }
    }

That would also open the possibility to define things like which format string to use when binding this item to a template placeholder (very useful for e.g. DateTime or numerical values!)

**Comment by thefringeninja** [comment]
:+1:. If you are putting your entities on the wire you are doing it wrong anyway.

At the very least, allow us to explicitly turn on a 'running with scissors' mode.

**Comment by mikebridge** [comment]
It's be great to see security as a separate concern outside DotLiquid.  C# is more secure than Ruby and so DotLiquid's security apparatus is redundant.  It's trivial for a C# developer to do this himself.
