### ISSUE TITLE
Math filters: incorrect rounding

### ISSUE THREAD

**Issue by mikebridge** [dotliquid/dotliquid#124]
in ExpressionUtility.CreateExpression, Expression.Convert is casting numbers into the type of the input parameter, so if you multiply an int with a decimal operand, the mantissa is truncated on the operand.  

This test fails with "3" instead of "4.5":

```c#
    [Test]
    public void TestTimesRounding()
    {
        Helper.AssertTemplateResult("4.5", "{{ input | times:operand }}", Hash.FromAnonymousObject(new { input = 3, operand = 1.5 }));
    }
```

**Comment by haf** [comment]
@mikebridge Would be a great PR, even now when you've written your own dotliquid.
