### ISSUE TITLE
For loop over a Dictionary<string,string>

### ISSUE THREAD

**Issue by jogibear9988** [dotliquid/dotliquid#126]
I did a for loop over this, and tried to access the key and value without success!

With the official Liquid Syntax this should be item[0] and item[1] if my iterator is named item!

I think this could be changed, but the Liquidize function returns the value for KeyValuePair<string, object>, I think thisn then also needs to be changed?

**Comment by jogibear9988** [comment]
I've created a commit, with wich this works, but I don't know is this is correct!

https://github.com/jogibear9988/dotliquid/commit/74b170b56b96bfaf0463acfd1c265e680ad64cd9

**Comment by jogibear9988** [comment]
I've also created a Pull req. https://github.com/dotliquid/dotliquid/pull/127 but it's based on my previous pull req...

**Comment by KyleAllaire** [comment]
Just to improve searchablility a bit: indexing into a KeyValuePair results in `Liquid error: Unable to cast object of type 'System.Int32' to type 'System.String'`

**Comment by jogibear9988** [comment]
don't undestand what you mean

**Comment by KyleAllaire** [comment]
That is the error I was getting when accessing item[0] or item[1] inside a for-loop which I believe your pull request will fix. It took me quite a while to find this issue, so I thought I'd add the previous comment to make it easier for others.

**Comment by haf** [comment]
#127 is the way to go when rebased.
