### ISSUE TITLE
Day of month (%-d) does nothing when zero-padding and Ruby syntax

### ISSUE THREAD

**Issue by cameron-mailoutinteractive** [dotliquid/dotliquid#134]
When you normally format a date using Ruby syntax you do something like:

{{ myDate | date: "%m %d, %Y" }}
If the myDate is January 12, 2014, then I'd get
01 12, 2014

Fine.

If myDate is:
January 4, 2014, then I'd get:
01 04, 2014

But if I want:
01 **4**, 2014
I should be able to have:
{{ myDate | date: "%m %-d, %Y" }}
But that returns:
01 %-d, 2014

**Comment by haf** [comment]
Please rebase #138
