### ISSUE TITLE
Is it really required to make Variable.Render(Context) internal?

### ISSUE THREAD

**Issue by canerelci** [dotliquid/dotliquid#137]
When you need to render just a variable to use its response as string, you have to create a separate TextWriter and get results from there. But there is an internal version of Render, which only takes the context and returns string. It would make the life easier to make it public.

**Comment by rdumont** [comment]
:+1: I have also needed it more than once.

**Comment by canerelci** [comment]
I created a fork and going to fix/change things like these. But I am working on a new feature, passing key:value[,key:value] parameters to filters, which will take a little longer than I think. I will then commit and request a PR.

**Comment by haf** [comment]
PR would indeed be nice 👍
