### ISSUE TITLE
Replace filter different implementation to ruby Liquid

### ISSUE THREAD

**Issue by dkarzon** [dotliquid/dotliquid#139]
I have noticed the replace filter has a different implementation to the original ruby implementation.

Looks like dotliquid does a regex replace where liquid does a literal replace.

Example: 
`{{ 'test.123' | replace: '.', '-'}}`
Under dotliquid returns `'--------'`
Under ruby liquid returns `'test-123'`

This is a problem when using something like Pretzel locally and GIthub page. Locally replaces work with regex then on the server it works with literals.

**Comment by canerelci** [comment]
The same bug appears when you need to replace '+' or '*' signs so an exception is required for these one character replacements. I did fix this on the version I forked but not ready to commit yet. But I can share the changes with you if you need it.

**Comment by dkarzon** [comment]
Is there a reason this was implemented as a regex instead of a literal replace?

Thanks @canerelci I can see where the problem is, just wanted to check why it was done this way before attempting a PR.

**Comment by rdumont** [comment]
This really is a problem, and one with an easy fix. But I don't see how we can fix it without possibly breaking some people who are already depending on the current behavior. This should be fixed on 2.0.

**Comment by dkarzon** [comment]
You could potentially have a `replaceregex` filter that uses the current behaviour then `replace` will change to be the same as the ruby version. Still a breaking change but will support people using it as it currently works.

**Comment by haf** [comment]
Please PR this to master and we'll release v2.0 come monday.
