### ISSUE TITLE
Multiple input values/array literals

### ISSUE THREAD

**Issue by BrianVallelunga** [dotliquid/dotliquid#141]
Is there a way to pass a literal array to a filter that accepts arrays? For example, I'd like to write:

{{ 10, 21, 34, 56 | SpecialFilter }}

With SpecialFilter taking an array of ints. Is this possible, or do I have to quote this to make it work? I know I can do: {{ '10, 21, 34, 56' | SpecialFilter }} but that's not as clean.

**Comment by mikebridge** [comment]
There are no array literals in liquid, but if your filter can handle an array of strings you can use split as a workaround:

```liquid
    {% assign my_array = "10,21,34,56" | split: "," %}
```

**Comment by rdumont** [comment]
So far the uses of declaring arrays inside a template are very few. Therefore the Liquid language doesn't provide a native way of doing so. But any time you really feel the need to do so, you can just do as @mikebridge said, which is the most widespread workaround.
