### ISSUE TITLE
Implement include_relative

### ISSUE THREAD

**Issue by dkarzon** [dotliquid/dotliquid#142]
Similar to `{% include %}` tag except it doesn't expect files to be in the _includes folder, instead they are relative to the tag is used from.

http://jekyllrb.com/docs/templates/#including-files-relative-to-another-file

**Comment by rdumont** [comment]
The `include_relative` tag shouldn't be in the standard DotLiquid implementation, as it has to do with a specific file system (in your example, Jekyll, which expects an `_includes` folder).

I'm going to close this issue, but if you'd like to have similar functionality, you should implement [`IFileSystem`](https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/FileSystems/IFileSystem.cs) and your own `include_relative` tag. For reference, see the [`LocalFileSystem`](https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/FileSystems/LocalFileSystem.cs) class.

**Comment by dkarzon** [comment]
Thanks, I'll take a look at that.
