### ISSUE TITLE
Please indicate the line and context when reporting a parse error

### ISSUE THREAD

**Issue by bradphelan** [dotliquid/dotliquid#144]
I get a parse error and it could be any one of a hundred blocks. It would be nice if the line number of the parse error was given in the message then the user could immediately fix the and keep going.

**Comment by canerelci** [comment]
+1
Most of the time I dig into all source while debugging to just find a similar error. I don't know if the original Liquid has the same behavior, but it would really nice to have more descriptive error and exception messages. I will take care of it soon (I will have to) if nobody else has time to...

**Comment by rdumont** [comment]
We are considering a rewrite of the parser, so that will probably come with it! I agree that it is much needed.
