### ISSUE TITLE
Add a RegisterTag method

### ISSUE THREAD

**Issue by laedit** [dotliquid/dotliquid#146]
I use MEF to allow the user of my app to add plugins and for DotLiquid add Tags and Filters.
I also use MEF to do all dependency injection work and avoid the use of static classes.

But since DotLiquid.Template.RegistarTag works only with type and instanciate the tag itself the dependency injection can't work.

Is it possible to add a RegisterTag method which takes directly a variable of type Tag?

If you are ok with the idea I can propose a PR.

**Comment by tgjones** [comment]
I don't think you'd want to directly register a `Tag` instance, because then that since instance would be re-used in all parsed templates, whereas a new instance should be created for every usage in a template. I guess you'd want to register an `ITagFactory` sort of thing?

**Comment by laedit** [comment]
In my case that's not a problem, the `Tag` instance will contain only common data for all templates.
But an `ITagFactory` will works as well.
