### ISSUE TITLE
Losing offset when using Date filter on a DateTimeOffset object

### ISSUE THREAD

**Issue by nadeemmar** [dotliquid/dotliquid#149]
I have a DateTimeOffset object with +4 hours offset but when using the date filter, it always loses this offset. This is due to parsing the input just after you convert it to a string (input.ToString()) on the date filter. 

I have worked around this by introducing my own filter that uses DateTimeOffset. I am more than happy to fix this and issue a pull request but i thought I would this here to see if you already made plans to fix it or not.

Thanks.

**Comment by haf** [comment]
This would be a great PR.
