### ISSUE TITLE
RegisterSafeType Throws a NullReferenceException when registering enum type

### ISSUE THREAD

**Issue by shekky** [dotliquid/dotliquid#152]
I am getting a NullReferenceException when trying to register an enum here's my code:

```
DotLiquid.Template.RegisterSafeType(GetType(RateType), Function(r) r.ToString)
```

I've also tried a different overload with an array of values instead of the lambda expression and I still get the same exception

**Comment by haf** [comment]
There's a pr #118 that needs rebasing, could you please do this?
