### ISSUE TITLE
times is not working as in ruby

### ISSUE THREAD

**Issue by Woland2k** [dotliquid/dotliquid#153]
Ruby has the following test:

assert_template_result "6", "{{ '2.1' | times:3 | replace: '.','-' | plus:0}}"

It seems as .net version interprits this differently, mainly '2.1' will be a string instead of decimal. Has anyone tried modifying times to handle this scenario or should it be done in some other, more global way?

**Comment by Woland2k** [comment]
Actually after studding ruby implementation a bit more, they no longer support strings in math functions. I implemented that feature in the following commit: https://github.com/VirtoCommerce/dotliquid/commit/16202dd82663ad94c08f5f70fff048ba46e713bd

That branch includes more features, including handling named parameters and other features from shopify implementation. Will merge is as soon as time allows unless someone else is willing to do that.

**Comment by haf** [comment]
Hi @Woland2k, could you please PR your changes?
