### ISSUE TITLE
Cached template not working

### ISSUE THREAD

**Issue by Woland2k** [dotliquid/dotliquid#154]
It seems according to documentation that caching parsed template should work across multiple threads (as in web application) and the same template can be reused many times instead of being parsed. However it doesn't seem to be the case as collection is modified error is generated in the following test:

        [Test]
        public void TestCachedTemplateRender()
        {
            Template template = Template.Parse(@"{% assign foo = 'from instance assigns' %}{{foo}}");

			var parallelOptions = new ParallelOptions
			{
				MaxDegreeOfParallelism = 30
			};

            Parallel.For(0, 10000, parallelOptions, (x) => Assert.AreEqual("from instance assigns", template.Render()));
        }

Anyone else experience the same issue?

**Comment by Woland2k** [comment]
Changing Context class function to the one below seem to solve the issue:

		private void SquashInstanceAssignsWithEnvironments()
		{
			Dictionary<string, object> tempAssigns = new Dictionary<string, object>(Template.NamingConvention.StringComparer);

			Hash lastScope = Scopes.Last();
		    var allKeys = lastScope.Keys.ToArray();

            foreach (string k in allKeys)
				foreach (Hash env in Environments)
					if (env.ContainsKey(k))
					{
						tempAssigns[k] = LookupAndEvaluate(env, k);
						break;
					}

			foreach (string k in tempAssigns.Keys)
				lastScope[k] = tempAssigns[k];
		}

**Comment by haf** [comment]
Yes, you're right. It would seem @303248153 has fixed it but there's been no PR yet.
