### ISSUE TITLE
Nested Dictionary in for loop

### ISSUE THREAD

**Issue by fan711** [dotliquid/dotliquid#157]
A multiple nested Dictionary works fine if variables are addressed directly. In a for loop however variables are not returned as expected. Here's a test to illustrate the issue:

        [Test]
        public void TestForWithDictionary()
        {   
            var dictionary = new Dictionary<string, object> { {
                "People", 
                new Dictionary<string, object> {
                    { "ID1", new Dictionary<string, object>{ { "First", "Jane" }, { "Last", "Green" } } },
                    { "ID2", new Dictionary<string, object>{ { "First", "Mike" }, { "Last", "Doe" } } }
                }
            } };

            // works fine
            Helper.AssertTemplateResult("Jane", "{{ People.ID1.First }}",
                Hash.FromDictionary(dictionary));

            // does not work in a loop
            Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.First }}{%endfor%}",
                Hash.FromDictionary(dictionary));
        }

**Comment by haf** [comment]
Hi @fan711 – do you think you could PR a fix for this?
