### ISSUE TITLE
add support for unregistering tags

### ISSUE THREAD

**Issue by JasonHenson** [dotliquid/dotliquid#159]
We are having an issue where multiple tags with the same name are colliding because registered tags are global. We was hoping that a method to unregister tags could be added to the template class.

		public static void UnregisterTag(string name)
		{
			if (Tags.ContainsKey(name))
				Tags.Remove(name);
		}

**Comment by AhChris** [comment]
I have been looking for a way to do this too. I have a custom tag that I want available to some templates, but not others.

I tried overriding (copy paste w/slight mod) the parse method of my block tag, to treat this tag as "unknown" but I ran into a lot of issues with internal and private methods.

Also tried inheriting the Template class, and adding a method like UnregisterTag, but had issues with the private Tags collection.

The last idea was to download the entire source and compile it ourselves to add a method like this. Seems like overkill though.

In the ruby implementation, you can pass a null type into the register tag method to remove it. That is not possible in C# though.

**Comment by haf** [comment]
The better way to do this is to refactor the context into an instance instead of a global static.
