### ISSUE TITLE
Add json filter support

### ISSUE THREAD

**Issue by avishnyakov** [dotliquid/dotliquid#161]
Seems that liquid has 'json' filter, according the documentation here:
https://docs.shopify.com/themes/liquid-documentation/filters/additional-filters#json

However dotliquid does not seem to have it yet.
At least {{ myObject | json }} does nothing.

Is that by design or missed feature?
Also, is there some kind of mapping between liquid and dotliquid  filters support?

**Comment by haf** [comment]
It's a missing feature. We'd love a PR for it.
