### ISSUE TITLE
ruby boolean methods posted_successfully?

### ISSUE THREAD

**Issue by Woland2k** [dotliquid/dotliquid#162]
Hi, 

shopify supports this so called bolean methods as described here: https://docs.shopify.com/themes/liquid-documentation/objects/form#form-posted_successfully

{% if form.posted_successfully? %}
    Comment posted successfully!
{% else %}
    {{ form.errors | default_errors }}
{% endif %}

It seems not necessary for the .net implementation since we do have boolean type and can determine if the value is boolean or not, but still for compatibility sake, how would one go about adding such support in dotliquid? Would I just simply remove "?" if it is at the end and cast value to boolean? Where would I do that?

Any suggestion is appreciated.

**Comment by haf** [comment]
I would say it's an annotation in the AST but I'm just another user.
