### ISSUE TITLE
One more issue 'An item with the same key has already been added.''

### ISSUE THREAD

**Issue by avishnyakov** [dotliquid/dotliquid#166]
The following POCO give an issue 'An item with the same key has already been added.' in TypeResolution.TypeResolution() method:

```
  public class Entity 
    {
        public new MyType Type { get; set; }
    } 
```
Type gets messed up with the out of the box object.Type property.

**Comment by haf** [comment]
If this was PR-ed and merged, then this issue will have been solved.
