### ISSUE TITLE
allow cache template for tag include and extend

### ISSUE THREAD

**Issue by 303248153** [dotliquid/dotliquid#167]
I think the return type of  IFileSystem.ReadTemplateFile should be object not string.
In the moment tag extend will detect type is "Template" like
```
Template template = file as Template;
template = template ?? Template.Parse(file == null ? null : file.ToString());
```
but since ReadTemplateFile  return string so first expression always return null.
I will change it in my fork, but because it's a interface break I'll not create the pull request yet,

**Comment by haf** [comment]
This would be great to have as a PR.
