### ISSUE TITLE
Did you make any optimization tip related on this ?

### ISSUE THREAD

**Issue by nelero** [dotliquid/dotliquid#172]
An interesting serie of posts about how to optimize dotliquid.
Are those optimizations in the last version of dotliquid ?
http://stevelillis.blogspot.fr/search/label/DotLiquid

thanks

**Comment by tgjones** [comment]
@SteveLillis has done some great work there, and he opened this pull request: #131.

It includes some breaking API changes, so I can't merge it into the v1.x line as it is, but I'd gladly accept just the performance improvements part of it if they could be submitted in a separate PR.

**Comment by haf** [comment]
If this is given a new PR to master I'll release it as soon as there's build code in the repo that pushes nugets. If you want this feature in v2.0, that release probably happens monday next week (2016-07-25)
