### ISSUE TITLE
Optionally disable trimming

### ISSUE THREAD

**Issue by jhominal** [dotliquid/dotliquid#177]
## Option to disable ERB-inspired whitespace trimming around tags

While profiling the application that I am working on, it has come to my attention that, on some of the templates that we currently use, `Template.Parse` takes two thirds of its time on ERB-like trimming. (The template is about 18000 characters long)

I would like to know whether you would be open to adding an option that would suppress trimming.

**Comment by haf** [comment]
As long as it doesn't affect the output, or is opt-in, it would be a good feature if it also dramatically reduced time to render.

**Comment by microalps** [comment]
The linked PR enhances the performance of trimming to make this request unnecessary.
