### ISSUE TITLE
Use standard AngularJS markup on Liquid templates

### ISSUE THREAD

**Issue by Andrew-Orlov** [dotliquid/dotliquid#180]
By default AngularJS is using the same double curly braces for data binding on templates as Liquid. Is it possible to render Liquid templates with AngularJS markup in correct way and leave standard AngularJS '{{ ... }}'? It is important since some external AngularJS-plugins is using only this kind of markup.

**Comment by tgjones** [comment]
That's what the `{% raw %}` tag is for. You can use it to escape curly braces that you want to leave intact:

``` liquid
{% raw %}
{{ etc...
{% endraw %}
```

**Comment by Andrew-Orlov** [comment]
@tgjones Oh, I've found it in Shopify's docs already. Meanwhile, thanks for the answer - you're reveal my doubts.

**Comment by Andrew-Orlov** [comment]
And I've got another question - why's {{ '{{ ... }}' }} throws an exception?

**Comment by Andrew-Orlov** [comment]
There is an issue with `{% raw %}` tag.
`{% raw %} {{ some_angular_value }} {% endraw %}` will be rendered as expected, but 
`{% raw %} {{ some_angular_value {% endraw %}` gives an exception `DotLiquid.Exceptions.SyntaxException: raw tag was never closed`.

**Comment by haf** [comment]
@Andrew-Orlov Could you please send a PR fixing this?
