### ISSUE TITLE
Build on CoreCLR / .Net Core

### ISSUE THREAD

**Issue by gabriel-samfira** [dotliquid/dotliquid#181]
Hi,

First things first: Thanks for the great project!

Are there any plans to make this project CoreCLR compatible? There are just a couple of things that prevent it from building against CoreCLR. I did a quick hack here:

https://github.com/gabriel-samfira/dotliquid/commit/db43fd6dc3dca4811bdc365d45172399f4c6f67e

to build against the Windows Nano server TP4 build of CoreCLR.

Thanks!

**Comment by matthewrk** [comment]
Is there any traction with this?, particularly now that core is rc2 final.

**Comment by gabriel-samfira** [comment]
We are actually using IT:

https://github.com/cloudbase/juju-powershell-modules/tree/add-templating/Templating

Which is used in some windows juju charms.

**Comment by gabriel-samfira** [comment]
Forgot to mention, Window Nano Server juju charms :-)

**Comment by jindovu** [comment]
Now .NET upgrade .NET Core RC2 run on Linux, Window OS, I build a system using dotLiquid to generate template site but dotLiquid doesn't support for .NET core

**Comment by 303248153** [comment]
Added .net core support in my fork.
https://github.com/zkweb-framework/dotliquid/commit/b49ab934d3c61bd2edbf416abbbc72a614527a73
But I do lots of change before so I can't easliy create a PR.

**Comment by jindovu** [comment]
Thank you for your help, it's really usefully

**Comment by haf** [comment]
We'd love a PR making this a reality.

**Comment by haf** [comment]
Ping

**Comment by gabriel-samfira** [comment]
I currently have no time to allocate to this. If I free up in the next couple of weeks, I can have a look at creating a PR.

**Comment by tbolon** [comment]
The PR #204 now works.

There is still an issue regarding nuget package version (appveyor is locked on 1.0.0). Maybe it can be fixed after merge.

**Comment by haf** [comment]
@tbolon Excellent work – I've been following you throughout the day 👍

**Comment by haf** [comment]
Closing in favour of #204
