### ISSUE TITLE
Integration between dotliquid and with .NET Core

### ISSUE THREAD

**Issue by jindovu** [dotliquid/dotliquid#185]
Hello everyone,
      Now .NET upgrade .NET Core RC2 run on Linux, Window OS, I build a system using dotLiquid to generate template site, please let me know how can I integration between dotLiquid and .NET Core RC2

Thank you so much.

**Comment by haf** [comment]
Yes, we'd love a PR making that possible!

**Comment by haf** [comment]
Duplicate of #181
