### ISSUE TITLE
Integer property not output correctly

### ISSUE THREAD

**Issue by sunblognuke** [dotliquid/dotliquid#192]
Hey guy, 

why the integer property not render? The coding sample like that:

```c#
var liquidTemplate = @"<ul>
                    {% for item in categoryset %}
                        <li><a href=""{{item.link}}"">{{ item.title }}</a><label>{{ item.samplecount }}</label></li>
                    {% endfor %}
                    </ul>";


[LiquidType("Title", "SampleCount", "Link")]
 public class CategoryInfo 
```

The property title and link work as expected but samplecount just output blank.

Does anyone have any examples of objects using int properties and DotLiquid?

Appreciated much.

**Comment by laedit** [comment]
Try with `item.sample_count`.
The [default casing is based on ruby](https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers#filter-and-output-casing) so a property with capitalized letters will use `_` to separate words.
