### ISSUE TITLE
Release v3 for .Net Core

### ISSUE THREAD

**Issue by haf** [dotliquid/dotliquid#194]

**Comment by HamedFathi** [comment]
1+
I am eagerly awaiting for this version
Is there a specific release date?
please release as soon as possible !

**Comment by haf** [comment]
Hi @HamedFathi – AFAIK noone has done the job to support .Net Core. Would you be willing to submit a PR for it, please?

**Comment by HamedFathi** [comment]
@haf    You can check my pull request "dotliquid .NET Core version".
I added new branch with .NET Core version, welcome dotliquid ;)

**Comment by rocifier** [comment]
Hi what's the status of that pull request?

**Comment by haf** [comment]
There aren't any open PRs
