### ISSUE TITLE
Writing out errors instead of throwing/collecting

### ISSUE THREAD

**Issue by pebezo** [dotliquid/dotliquid#197]
The following code:

```
template = Template.Parse(@"testing... {% assign my_variable = 123 %} {% if my_variable == 123 and not something %} foo {% endif %}");
template.Render();
```

outputs: "Liquid error: Unknown operator something" which is correct, but the output is part of the final string. From a quick search it looks like the code gets here:

https://github.com/dotliquid/dotliquid/blob/99a1dbb651e727c0f30404afd8869635baa73c23/src/DotLiquid/Block.cs#L142

Was this intentional? I would expect this to be either part of `template.Errors` or to throw an error. Just writing it out on the page is not workable (actual errors would get missed).

**Comment by pebezo** [comment]
To clarify: I could send a PR with this change, just want to make sure it's within the design of the project. However, if the current design calls for an in-line error output then we may need to fork the project -- something we don't want. Thanks.

**Comment by tgjones** [comment]
Have you looked at `RenderParameters.RethrowErrors`?

https://github.com/dotliquid/dotliquid/blob/99a1dbb651e727c0f30404afd8869635baa73c23/src/DotLiquid/RenderParameters.cs#L20

**Comment by pebezo** [comment]
That did the trick, thank you!!
