### ISSUE TITLE
please support sub-templates and nested templates

### ISSUE THREAD

**Issue by HamedFathi** [dotliquid/dotliquid#198]
please consider this class :
```
var dep =
            new Department
            {
                Name = "Jack",
                Employees = new List<Employee>
                {
                   new Employee()
                   {
                       Name = "E1",
                       Kids = new List<Kid>()
                       {
                           new Kid
                           {
                               Name = "K1"
                           },
                           new Kid
                           {
                               Name = "K2"
                           },
                           new Kid
                           {
                               Name = "K3"
                           },
                           new Kid
                           {
                               Name = "K4"
                           }
                       }
                   },
                   new Employee()
                   {
                       Name = "E2",
                       Kids = new List<Kid>()
                       {
                           new Kid
                           {
                               Name = "K5"
                           },
                           new Kid
                           {
                               Name = "K6"
                           }
                       }
                   },
                   new Employee()
                   {
                       Name = "E3",
                       Kids = new List<Kid>()
                       {
                           new Kid
                           {
                               Name = "K7"
                           }
                       }
                   }
                }
            };

```
so I need to define sub-template something like :
```
{{ Name }}
{% for e in Employee %}
  {{ EmployeeTemplate e }} // a Template can be an object for itself as input
{% endfor %}


EmployeeTemplate :
{% for k in Kids %}
  {{ KidTemplate k }}
{% endfor %}


KidTemplate :
{% for o in OBJECT %}
  {{Name}}
{% endfor %}
```

and result :
```
Jack
E1
K1
K2
K3
K4
E2
K5
K6
E3
K7 
```     

I need template as standalone block of strings so I want to know dotliquid support it or not ? if standalone templates support so Can we define nested templates or not ?

**Comment by pebezo** [comment]
I believe (still new with DotLiquid) that you need to either have your classes (Department, Employee, etc) inherit from Drop or use [LiquidType("Field1", "Field2", ...)] to decorate those classes.

**Comment by HamedFathi** [comment]
for me Result is not important, existing sub template and nested template is very important so Can you reform my code with your idea ?

**Comment by laedit** [comment]
As stated in the [wiki](https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers#includes), you can include partial templates.
Is that what you are searching?

**Comment by pebezo** [comment]
Sorry, I guess I misunderstood your question. To add to what @laedit said, here's the code for the "include":

https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/Tags/Include.cs

You should be able to create custom tags (like include) that would look somewhere else instead of the file system.

**Comment by HamedFathi** [comment]
@laedit Yes but NO ! partial templates works as file based not string based although it is not important but another reason with highly important is all template should have standalone object for itself but in dotliquid when I use partial template I should have correct class property chains e.g

```
_tmpl1.liquid >>
{% for item in user.tasks -%}
	{% include "tmpl2" %}
{% endfor -%}
```

```
_tmpl2.liquid >>
  <li>{{ item.name }}</li>
```
```
C# Source >>
 Template.FileSystem = new LocalFileSystem(@"PATH");

            string templateCode = @"<ul>
{% include ""tmpl1"" %}
</ul>";

            Template template = Template.Parse(templateCode);

            string result = template.Render(Hash.FromAnonymousObject(new
            {
                user = new User
                {
                    Name = "Tim Jones",
                    Tasks = new List<Task> {
                                        new Task { Name = "Documentation" },
                                        new Task { Name = "Code comments" }
                                      }
                }
            }));
```

tmpl1 is not standalone only works when I have **user.tasks** not **tasks** so when I have **employee.tasks** this template is useless !

**Comment by laedit** [comment]
This is possible by assigning the variable `tasks` in parent templates:
```
{% assign tasks=user.tasks %}
```
And use only `tasks` in `_templ1.liquid`.

**Comment by HamedFathi** [comment]
@laedit  thanks I check it ! but Is there any way for having string based {{include}} not file based ?

**Comment by laedit** [comment]
Not that I know, but like @pebezo said you can implement your own `FileSystem` to make it string based.

**Comment by HamedFathi** [comment]
@laedit about your assign solution this is work but not standalone If I correct I should change my template to 
```
{% assign tasks=user.tasks %}
{% for item in tasks -%}
	{% include "tmpl2" %}
{% endfor -%}
```

yes for 'for' statement model is standalone but for whole template not because when I want to use template with another object must change {{assign}} in my 'template.liquid' file for example 
```
{% assign tasks=employee.tasks %}
{% for item in tasks -%}
	{% include "tmpl2" %}
{% endfor -%}
```

template in dotliquid with this solution is not standalone yet  :(

**Comment by laedit** [comment]
`parent`
```
{% assign tasks=employee.tasks %} // or user.tasks
{% include ""tmpl1"" %}
```

`tmpl1`
```
{% for item in tasks -%}
    {% include "tmpl2" %}
{% endfor -%}
```

`tmpl2`
```
  <li>{{ item.name }}</li>
```
