### ISSUE TITLE
`raw`\`endraw` can't escape string that contains {{ double opening curly brace

### ISSUE THREAD

**Issue by skfd** [dotliquid/dotliquid#199]
I was trying to do a trivial thing of rendering mixture of liquid and handlebars. But this case renders `{%raw%}` as if it's not a control tag.

Template:

``` liquid
{% for item in user.tasks -%}
  <li>{{ item.name }}</li>
  {%raw%}<li>{{ item.name {%endraw%} {%raw%}}}</li>  {%endraw%}
{% endfor -%}
```

Rendered as:

``` html
  <li>Documentation</li>
  <li>{{ item.name {%endraw%} {%raw%}}}</li>  
  <li>Code comments</li>
  <li>{{ item.name {%endraw%} {%raw%}}}</li>  
```

Should I somehow escape {{ symbols between raw\endraw tags?

**Comment by microalps** [comment]
Issue in reference library - https://github.com/Shopify/liquid/issues/204
