### ISSUE TITLE
Increment/Decrement tag not existing

### ISSUE THREAD

**Issue by davidpelayo** [dotliquid/dotliquid#205]
As specified on the oficial Shopify Liquid documentation, there are two tags to iterate over variables' values, which aren't existing in dotliquid, which are:
- Increment
- Decrement

[See this doc](https://help.shopify.com/themes/liquid/tags/variable-tags).

It would be nice to have them.

**Comment by laedit** [comment]
Sadly we don't have time to add this ourselves, but we are welcoming any PRs :smile:
