### ISSUE TITLE
Is Template.Render thread safe?

### ISSUE THREAD

**Issue by hellosnow** [dotliquid/dotliquid#206]
Hi I'm using dotliquid to generate html files, and could I ask whether Template.Render is thread safe or not?

**Comment by intval** [comment]
Not at all. 
Simple templates "Hello {{ name }}" would work, but templates with variables, assignments includes and captures are unpredictable.

	[Test]
	public void TestConcurrentLiquid()
	{
		var tpl = Template.Parse("Hello {{name}}  " +
								 "{% assign val = num %} " +
								 "{%capture out%} " +
								 "   cool" +
								 "   {% assign val = num+1 %}" +
								 "{% endcapture%} " +
								 "{% if x %} {{out}} {%endif%}" +
								 "{{ val }}");

		var input = new []
		{
			new { name = "a", x = false, num = 9},
			new { name = "bla", x = true, num = 99},
		};

		// Single thread execution, for later comparison
		var expected = new[]
		{
			tpl.Render(Hash.FromAnonymousObject(input[0])),
			tpl.Render(Hash.FromAnonymousObject(input[1]))
		};

		// Crashes with different errors or inconsistent output
		Parallel.For(0, 200000, new ParallelOptions {MaxDegreeOfParallelism = 8}, i =>
			{
				Assert.AreEqual(expected[i % 2], tpl.Render(Hash.FromAnonymousObject(input[i%2])));
			}
		);

	}

On a side note, assignment of `val = x + 1` doesn't work either ;/

**Comment by hellosnow** [comment]
Thanks for the sample! Then I'll handle multiple threads in my side.

**Comment by microalps** [comment]
@daviburg I believe this issue is safe to close?
