### ISSUE TITLE
Does DotLiquid support .NET Framework 4.5?

### ISSUE THREAD

**Issue by theronic** [dotliquid/dotliquid#208]
When I try to add DotLiquid 2.0.55 via NuGet to my ASP.NET MVC project running .NET Framework 4.5 project, I see this error:

```
Installing 'DotLiquid 2.0.55'.
Successfully installed 'DotLiquid 2.0.55'.
Adding 'DotLiquid 2.0.55' to iFix.Services.
Uninstalling 'DotLiquid 2.0.55'.
Successfully uninstalled 'DotLiquid 2.0.55'.
Install failed. Rolling back...
Could not install package 'DotLiquid 2.0.55'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by laedit** [comment]
Actually dotliquid support the full .net framework 4.5.1 and NetStandard 1.3.

**Comment by devisscher** [comment]
Running into issues at install as well, my build is .net 4.5

```You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. ```

**Comment by bradphelan** [comment]
If you download the nuget package and open it you can see that it does support 4.5.1 as well as netstandard 1.3

![image](https://cloud.githubusercontent.com/assets/17650/21339843/a6f9b406-c682-11e6-9818-bf0b13023d89.png)

**Comment by bogdan2** [comment]
I just had the same issue with version 2.0.64. My project targets 4.5. The version I ended up using is 2.3.0.
When I changed the target to 4.5.1 2.0.64 worked as well. Does the library have to target 4.5.1 specifically?

Thanks

**Comment by laedit** [comment]
It is the case right now but I will see if we can target 4.5 instead of 4.5.1.
