### ISSUE TITLE
Are "complex" expressions supported?

### ISSUE THREAD

**Issue by pebezo** [dotliquid/dotliquid#212]
Could you confirm that "complex" expressions, like (1 == 1 or 2 == 3) and (4 == 4) are not supported? From what I can tell, it doesn't parse properly -- sort of tries to -- but it doesn't error out either (when finding a parenthesis).

Something like this would fail:

```
Assert.AreEqual("  true  ", Template.Parse(" {% if (1 == 1 or 2 == 3) %} true {% else %} false {% endif %} ").Render());
Assert.AreEqual("  true  ", Template.Parse(" {% if (1 == 1 or 2 == 3) and (4 == 4) %} true {% else %} false {% endif %} ").Render());
```

**Comment by microalps** [comment]
From the Liquid documentation at https://shopify.dev/docs/themes/liquid/reference/tags/control-flow-tags#multiple-conditions-and-or
> You cannot use parentheses to simulate an order of operations and control the order of operator evaluation. Parentheses are invalid characters within Liquid tags and prevent your tags from working.
