### ISSUE TITLE
Is inner objects supported in template?

### ISSUE THREAD

**Issue by officeclip1** [dotliquid/dotliquid#213]
I have created an object with a few inner objects at two levels:
```
class TopLevel: Drop {
  public string previewTitle {get; set;}
}

class PreviewObject: Drop {
  public PreviewObject(){
    topLevel = new TopLevel();
    topLevel.previewTitle = "My Title";
    test = "My Test";
  }
  public TopLevel topLevel {get; set;}
  public string test {get; set;}
}
```
Now I created the following liquid template
```
<p>{{ previewObject.topLevel.previewTitle }}</p>
<p>{{ previewObject.test }}</p>
```
The first line is showing as empty and the second line shows the correct value. Is it some programming issue or this inner objects cannot be used?

**Comment by laedit** [comment]
By default the ruby casing is used: https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers#filter-and-output-casing

Try with:
```liquid
<p>{{ preview_object.top_level.preview_title }}</p>
<p>{{ preview_object.test }}</p>
```

**Comment by officeclip1** [comment]
> <p>{{ preview_object.top_level.preview_title }}</p>
> <p>{{ preview_object.test }}</p>

Tried this and getting the same result.

**Comment by laedit** [comment]
If you have used `previewObject` in your hashed anonymous object you have to use it in your template but use the ruby casing for all other properties.
Otherwise change also your anonymous object:
```csharp
template.Render(Hash.FromAnonymousObject(new { preview_object = new PreviewObject() }));
```
Please read https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Drops to have all information about drops.
