### ISSUE TITLE
Is there any way to do date arithmetic

### ISSUE THREAD

**Issue by skdutta-ga** [dotliquid/dotliquid#214]
Say I want to subtract a few days to the date, in liquid we can do something like:

`my_date |  date: "%s" | minus : 604800`

is there an equivalent or workaround in dotliquid?

**Comment by laedit** [comment]
Please, when you report a bug add the error message.
In this case, I think it's because you try to subtract a number to a date.
A pull request would be welcome 😄

**Comment by icnocop** [comment]
[Pathoschild.NaturalTimeParser](https://github.com/Pathoschild/NaturalTimeParser) has a plugin for DotLiquid that can do this

So for example `{{ 'today' | as_date | date_offset:'30 days' | date:'yyyy-MM-dd' }}`
