### ISSUE TITLE
Run-Time Drop Validation

### ISSUE THREAD

**Issue by anton-gogolev** [dotliquid/dotliquid#215]
Wouldn't it be cool if one could:

    var template = Template.Parse("...");
    template.EnsureDropValid(typeof(MyCustomDrop));

which would recursively check all `{{ drop.placeholder.values }}`, walk over all `{% for i in item %}` loops and otherwise ensure that the `MyCustomDrop` does indeed contain all the properties required to render a `template`?

The only difficulty I see is with handling of "catch-all" drops (there's nothing one could realistically check when those are present), but otherwise I'm eager to implement such a feature.

Thoughts?

**Comment by albertospelta** [comment]
My PR #224 appears to be similar to your issue.

**Comment by microalps** [comment]
@anton-gogolev can you confirm the changes mentioned above fully resolve the need? I know 5 years has passed but if you can provide an update it would be appreciated. Will close this ticket in one weekifno response.

**Comment by microalps** [comment]
No response forthcoming (or expected to be honest). Closing.
