### ISSUE TITLE
why is Flatten() used in Sort()?

### ISSUE THREAD

**Issue by rolandbaer** [dotliquid/dotliquid#228]
In the StandardFilters.cs class the Sort() method calls Flatten() if the given input is IEnumerable.

Why is this? For me it causes some trouble because when you give a List of Hash elements as input (e.g 3 Hash elements with 8 entries each) the list is flattened and the content of the hash elements (e.g. 24 elements) are then tried to be sorted.

Occured for me as i use pretzel and wanted to do a navigation like in jekyll (see http://jekyll.tips/jekyll-casts/navigation/ )

**Comment by microalps** [comment]
This is the behavior of the native ruby implementation. See https://replit.com/@microalps/LiquidWhereTests
