### ISSUE TITLE
How to get Value of Parameter URL?

### ISSUE THREAD

**Issue by agungwiseso** [dotliquid/dotliquid#229]
Hi, wanna ask.
I have url` http://domain.com/product?groupid=39`

How to get the value of **groupid** ?

`{% assign groupid = request.param['groupid'] %}`
Is that correct?

Thanks

**Comment by nuvan** [comment]
Hi @agungwiseso . How did you transformed the url parameters?
The templating engine doesn't transform urls into a request.param automatically.
Following the online editor ( http://dotliquidmarkup.org/try-online )
`
<p>{{ user.name | upcase }} has to do:</p>

<ul>
{% for item in user.tasks -%}
  <li>{{ item.name }}</li>
  {% assign art = user.name %}
  <li>{{ art }}</li>
{% endfor -%}
</ul>
`

The assign works as expected but the environment has the variables properly created.

**Comment by laedit** [comment]
There is no automatic parsing of url variables or tag / filter which allow it.
But a PR is always welcome :)
