### ISSUE TITLE
Documentation: Contributing system requirements

### ISSUE THREAD

**Issue by icnocop** [dotliquid/dotliquid#231]
Hi.

Thank you for dotliquid.

When I open the DotLiquid.sln in Visual Studio 2015 I get the following error message:
```
---------------------------
Microsoft Visual Studio
---------------------------
The following error occurred attempting to run the project model server process (1.0.1). 
Unable to start the process. No executable found matching command "dotnet-projectmodel-server"
The project model server process provides intellisense, build, and reference information to Visual Studio and without it your experience will be very limited. Please try closing and reopening Visual Studio to see if that corrects the problem. Alternatively, check that the .NET Core SDK is properly installed.
---------------------------
OK   
---------------------------
```

Trying to build the solution anyway produces the following error message in all four projects:
```
*.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Windows 7 x64 SP1
Visual Studio 2015 Enterprise Update 3
.NET Core SDK 1.0.1 (x64)
Microsoft .NET Core 1.0.1 - SDK 1.0.0 Preview 2-0031313 (x64)
Microsoft .NET Core 1.0.1 - VS 2015 Tooling Preview 2

Any ideas what I'm missing?

Thank you.

**Comment by laedit** [comment]
We have moved to Visual Studio 2017 and .net Core 1.0.3, do you still have an error?

**Comment by icnocop** [comment]
Hi Jérémie.

I'm okay with closing this issue after adding these development requirements to the wiki for example.

Thank you! 😄

**Comment by laedit** [comment]
Yes, I was planing to do that ;)
