### ISSUE TITLE
How to sort an array in template?

### ISSUE THREAD

**Issue by janjaapjuh** [dotliquid/dotliquid#232]
Hi,

I want to sort an array on a property alphabetically.
How can this be done?

I've tried this but it doesnt work. It shows the ContactPersons but not sorted.
` {% assign SortedContactPersons = ContactPersons | sort: "DisplayName" %}
        {% for Contactperson in SortedContactPersons %}
        <tr>
            <td>{{ contactperson.DisplayName }}</td>
            <td>{{ contactperson.Department }}</td>
        </tr>
        {% endfor %}`

Thanks!

**Comment by nuvan** [comment]
Using the editor online ( http://dotliquidmarkup.org/try-online ):

```
<p>{{ user.name | upcase }} has to do:</p>

<ul>
{% for item in user.tasks -%}
  <li>{{ item.name }}</li>
{% endfor -%}
</ul>

{% assign sortedTasks = (user.tasks | sort: "Name") -%}

<ul>

{% for item in sortedTasks -%}
  <li>{{ item.name }}</li>
{% endfor -%}

  <li>{{ item.name }}</li>
</ul>
```
You need to add the parentises.
