### ISSUE TITLE
Compatible with .NET 3.5 to use in Unity3D?

### ISSUE THREAD

**Issue by patrickwolf** [dotliquid/dotliquid#237]
The website states that dotLiquid is still compatible with .NET 3.5: http://dotliquidmarkup.org/
Is that still the case? The reason I'm asking is that we'd like to use it from Unity3D.
Thanks!
Patrick

**Comment by laedit** [comment]
The lib is available for .net 4.5.1 and NetStandard 1.3, so I think not.
In the future NetStandard should be used by "full" framework project but it seems that it is not the case yet.

But it seems that the next version of Unity ([2017.1.0](https://unity3d.com/unity/roadmap)) will support [.net 4.6](https://forum.unity3d.com/threads/upgraded-mono-net-in-editor-on-5-5-0b9.438359/).

**Comment by laedit** [comment]
I confirm that we can't re-support .net 3.5 since it will introduce some security issues.
