### ISSUE TITLE
Is there a way to turn off errors being added to returned string when calling template.Render()?

### ISSUE THREAD

**Issue by dmstih** [dotliquid/dotliquid#240]
If you add a complex object that's not ILiquidizable etc. and try to use that object in the string you're parsing the error saying "Object 'x' is invalid because it is neither a built-in type nor implements ILiquidizable" is added to the string when you call template.Render(). Is there a way to turn off these errors being added to the actual rendered string and only having them show up in template.Errors?

Quick example:
// Lets say x is a complex object which has a property ThingName which is a string
string text = "My username is {{user}}. Object: {{complexObject.ThingName}}";
Template template = Template.Parse(text);
string resultText = template.Render(Hash.FromAnonymousObject(new {
    user = "foo",
    complexObject = x
}))

This would return the user fine but for the {{complexObject.ThingName}} it would replace that with the error message in resultText. So is there a setting or something similar which I can change that will just leave a blank space there if it errors? It does that if the object or property doesn't exist but not if it does and it's not liquidizable.

**Comment by Raju17** [comment]
Use RethrowErrors=true
template.Render(new RenderParameters { LocalVariables=Hash.FromAnonymousObject(new {
user = "foo",
complexObject = x
}), RethrowErrors=true})
