### ISSUE TITLE
template.render is returning "Index was Outside the bounds of the array" error.

### ISSUE THREAD

**Issue by Raju17** [dotliquid/dotliquid#242]
Getting negative value from key.GetHashCode(), debugged the DLL code. Using 1.7 version.
This error is coming after recent security patches on the server and in some developer machines also.

**Comment by laedit** [comment]
Can you provide more info?
Have you tried the latest version (2.0.96 to this day)?

**Comment by Raju17** [comment]
I cannot use latest version 2.0..96, because its on 4.5. We are using .Net Framework 3.5 version

**Comment by shaeebSP** [comment]
Hi @Raju17  ,
Were you able to fix it? I am facing the same issue.

**Comment by Raju17** [comment]
No, we are upgrading to 1.8 version to fix the issue.

**Comment by laedit** [comment]
Is the issue still present with v1.8?
If necessary we could bring back the .net 3.5 support be it will require a lot of work.

**Comment by Raju17** [comment]
Issue resolved in 1.8 and 1.8 is the latest version which will be supported in Dot Net Framework 3.5

**Comment by laedit** [comment]
Ok, thanks for the update.

**Comment by shaeebSP** [comment]
Thanks everyone. I could'not upgrade the Version , hence had to remove the last windows patches. 
I would appreciate if this could be officially notified and resolved for 1.7 Version as well.

**Comment by laedit** [comment]
What is stopping you to upgrading to v1.8?
It has a .net 3.5 version.

An update to the 1.7 is unlikely to happen, we are too few and struggle already to continue the current version.

**Comment by shaeebSP** [comment]
Hi @laedit,@Raju17 
Its actually an existing application using a third party DLL which runs on 1.7 Version of DotLiquid. And as we are not having their support as of now. So we are actually looking fir a workaround to let the business unaffected till the time we get their support.
I need one help from you. **Can you please help me identify , which particular patch module is causing this issue**. Below are the list of Patches I got removed from last window. After removing all of these it started working. 
KB4014504
KB4014579
KB4018271
KB4019263
KB4019264
If you guys could figure out , please reply. 
Thanks in advance.

**Comment by laedit** [comment]
I wasn't able to found much info from these KB.
But instead, it is maybe possible to take the source code as it [was for the 1.8 version](https://github.com/dotliquid/dotliquid/tree/b609b8e63c095c6f6bbddd255c09fb63e673fed3) and compile it with v1.7 in the project properties to make it accepted by the third party?

**Comment by Raju17** [comment]
These are the two patches: KB4014504, KB4014579.

Refactor the 1.7 dll and convert negative to positive value in the below functions, Then it will work.

In Util > WeakTable.cs file,  function TValue
  int index = key.GetHashCode() % this._buckets.Length;
   **index = System.Math.Abs(index);**

fuction TryGetValue,
   WeakReference weakReference;
      **index = System.Math.Abs(index);**

**Comment by laedit** [comment]
I can't push another 1.7, I don't have access to it. Only @tgjones have it I believe.
And if we push another 1.7 it will be 1.7.1, I don't think we can push a different binary with the same version number.
Have you tried the temporary solution in my previous comment?
The only permanent one is to get your third party vendor to update his product.

**Comment by sebastienros** [comment]
I 1.7 and 1.8 are API compatible, then you should be able to force 1.8 with a binding redirect.

**Comment by shaeebSP** [comment]
Thanks @Raju17 @laedit ,
Let me try above solutions and get back.

**Comment by laedit** [comment]
I confirm that we can't re-support .net 3.5 since it will introduce some security issues fixed with API available only since .NET 4.
