### ISSUE TITLE
CSharpNamingConvention is untestable

### ISSUE THREAD

**Issue by swiftMessenger** [dotliquid/dotliquid#247]
Since Template.NamingConvention is a static variable, all threads utilize the same value - which makes testing different values more difficult than necessary. Currently, in order to properly test the CSharpNamingConvention, the Template.NamingConvention variable has to be locked, changed, then restored to it's previous (default) value before being unlocked again in order to prevent interfering with other tests running at the same time.

In the interest of testability, I would recommend updating Template.NamingConvention to Template.DefaultNamingConvention and making the naming convention configurable per template (which would have to be done via the Context). It may be possible to do this without causing a breaking change (by aliasing Template.DefaultNamingConvention as Template.NamingConvention with a deprecated warning and adding an additional optional parameter to the Context constructor).

**Comment by haf** [comment]
Solved above.
