### ISSUE TITLE
%-d for date Ruby format is not rendered

### ISSUE THREAD

**Issue by cincuranet** [dotliquid/dotliquid#251]
### Dotliquid version
2.0.145

### Expected behavior
I'm using ` | date: "%-d %b %Y"` as a date format. I'd expect the `%-d` to be rendered the same way as in Ruby. That is, the day without left padding zero (if it's single digit).

I'm using `Liquid.UseRubyDateFormat = true;`.

### Actual behavior
The `%-d` stays in final output.

### Steps to reproduce the Problem (you can add files)

```
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
Liquid.UseRubyDateFormat = true;
var result = Template.Parse("{{ foo | date: \"%-d %b %Y\" }}").Render(Hash.FromAnonymousObject(new { foo = DateTime.UtcNow }));
Console.WriteLine(result);
```

**Comment by laedit** [comment]
Thanks for the issue! 😃 
It seems that we are missing some parts of ruby date format.
Sadly we are short in time and men right now, can you do a PR?

**Comment by cincuranet** [comment]
I'm not sure. I don't have much of spare time as well. 

BTW I think PR #138 did that already, but looks like it was not merged.

**Comment by laedit** [comment]
Thanks for noticing that.
I will take a look but the PR seems to needs some works before being merged.

**Comment by cincuranet** [comment]
Ignoring the whitespace changes (https://github.com/dotliquid/dotliquid/pull/138/files?w=1) it seems to be doable.

**Comment by laedit** [comment]
I was not aware of this option, thanks!
Nevertheless there is still some conflicts which I can't fix right now, hopefully in a few weeks.

**Comment by microalps** [comment]
This was also reported in #134 - DotLiquid does not support flags that are part of the ruby language https://www.rubydoc.info/stdlib/date/Date:strftime - I see a commit from @robin-parker above-  care to create a PR once it's ready? Or maybe someone can backport this - https://github.com/mikebridge/Liquid.NET/blob/master/Liquid.NET/src/Utils/StrFTime.cs
