### ISSUE TITLE
map and sort filters violate safe-type allowed members (Drops concept breach)

### ISSUE THREAD

**Issue by nytmo** [dotliquid/dotliquid#275]
### Dotliquid version
2.0.183

### Expected behavior
**map** and **sort** filters should obey safe-type allowed members collections.

### Actual behavior
**map** and **sort** filters access directly object members through reflection ignoring allowed members collection of the accessed type

### Steps to reproduce the Problem (you can add files)

	public class Employee
	{
		public string Name { get; set; }
		public decimal Salary { get; set; }
	}

	var template = DotLiquid.Template.Parse("{{employees | sort:'Salary' | map:'Name' | join:', '}} | {{employees | map:'Salary' | join:', '}}");
	DotLiquid.Template.RegisterSafeType(typeof(Employee), new[] { nameof(Employee.Name) });
	var result = template.Render(DotLiquid.Hash.FromDictionary(new Dictionary<string, object> {
		{ "employees", new [] { new Employee { Name = "A", Salary = 456 }, new Employee { Name = "B", Salary = 123 } } }
	}));

This results in:
`B, A | 456, 123`

But using the `Salary` property is prohibited as it's not declared as allowed member via RegisterSafeType method, so an empty string or null should be returned instead of its true value.

This is heavy security issue and it violates the Drops concept.

**Comment by nytmo** [comment]
I propose this solution, which solves not only the security breach, but also naming conventions of property used as a map filter's parameter (#272) and makes map filter resilient to null input (#269)

	public static IEnumerable Map(IEnumerable input, string property)
	{
		if (input == null)
			return null;

		List<object> ary = input.Cast<object>().ToList();
		if (!ary.Any())
			return ary;

		if ((ary.All(o => o is IDictionary)) && ((IDictionary)ary.First()).Contains(property))
			return ary.Select(e => ((IDictionary)e)[property]);

		return ary.Select(e => {
			if (e == null)
				return null;

			var drop = e as DropBase;
			if (drop == null)
			{
				var type = e.GetType();
				var safeTypeTransformer = Template.GetSafeTypeTransformer(type);
				if (safeTypeTransformer != null)
					drop = safeTypeTransformer(e) as DropBase;
				else
				{
					var attr = type.GetTypeInfo().GetCustomAttributes(typeof(LiquidTypeAttribute), 	false).FirstOrDefault() as LiquidTypeAttribute;
					if (attr != null)
						drop = new DropProxy(e, attr.AllowedMembers);
				}
			}
			return drop?.InvokeDrop(property);
		});
	}

**Comment by microalps** [comment]
This issue seems resolved, closing.
