### ISSUE TITLE
How to grab data from DataBase inside custom Tag

### ISSUE THREAD

**Issue by cbmek** [dotliquid/dotliquid#283]
Hi!
I'm creating my own custom tags, lets say `{% mydata 15 %}` where `15` is ID from database.
While rendering tag, I want to grab proper data from db and display it.

It would be bad idea to create connection to DB in every Tag `Initalize` method, so I want to pass my global `ApplicationDbContext` to Tag. I'm using AspNet Core (+DependencyInjection), so it would be nice to use already registered services.
Any ideas?

**Comment by laedit** [comment]
Hi,

you can use an [`ITagFactory`](https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/ITagFactory.cs), which is more flexible about Tag creation.
I haven't tested but I think that in the app initialization, once the `DbContext` instantiated, you can create a factory with it and register it in DotLiquid through `Template.RegisterTagFactory(...)`

**Comment by cbmek** [comment]
Thx @laedit!

In case anybody would ever need it, here is factory with it's own Tag:

```
public class MyTagFactory : DotLiquid.ITagFactory
    {
        public string TagName => "mytag";

        private readonly ApplicationDbContext _context;

        public MyTagFactory(ApplicationDbContext context)
        {
            _context = context;
        }

        public Tag Create() => new MyTag(_context);

        public class MyTag : DotLiquid.Tag
        {
            private readonly ApplicationDbContext _context;

            public MyTag(ApplicationDbContext context)
            {
                _context = context;
            }

            public override void Render(Context context, TextWriter result)
            {
                result.Write(_context.Something.Count().ToString());
            }
        }
    }
```

and this is how you register it:

```
Template.RegisterTagFactory(new MyTagFactory(_context));
```

But I'm still not sure where should I `RegisterTagFactory`, for now I went with Transient Service and it's constructor.

**Comment by laksh-parab** [comment]
@cbmek  did you find the answer to this question?

**Comment by microalps** [comment]
Seems issue is answered and you have this figured out. Closing unless you have open questions.
