### ISSUE TITLE
Generic classes incompatible with Template.RegisterSafeType?

### ISSUE THREAD

**Issue by watkinsmatthewp** [dotliquid/dotliquid#286]
### Dotliquid version: 2.0.231.0

Because dotLiquid does not support _member-level_ attribute decoration, I've created a custom attribute for my project and I'm registering the types and properties at run-time using the [`Template.RegisterSafeType()` method of drop registration](https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Developers#rules-for-template-rendering-parameters).

In other words, instead of the `LiquidType` class attribute like this...

```cs
[LiquidType("MyExposedValue")]
public class MyClass
{
  public string MyExposedValue { get; set; }
  public string MyHiddenValue { get; set; }
}
```

... I use my own custom dual-level attribute like this:

```cs
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Property, AllowMultiple = false)]
public class LiquidSafeAttribute : Attribute
{
}

[LiquidSafe]
public class MyClass
{
  [LiquidSafe]
  public string MyExposedValue { get; set; }
  // No [LiquidSafe] attribute on this property, therefore not exposed
  public string MyHiddenValue { get; set; }
}
```

Then on app startup, I reflect over the types in the assembly and pass the decorated properties into `Template.RegisterSafeType`:

```cs
foreach (var type in Assembly.GetExecutingAssembly().GetTypes())
{
  if (type.GetCustomAttribute<LiquidSafeAttribute>() != null)
  {
    Template.RegisterSafeType(type, type.GetProperties()
        .Where(p => Attribute.IsDefined(p, typeof(LiquidSafeAttribute)))
        .Select(p => p.Name).ToArray()
      );
  }
}
```

This works fine for everything... except generics:

```cs
[LiquidSafe]
public class MyClass<T>
{
    [LiquidSafe]
    public T MyExposedValue { get; set; }
    public string MyHiddenValue { get; set; }
}
```

For example, if I try to render a `MyClass<string>`, I get an error:

```txt
Liquid syntax error: Object 'DotLiquidTest.MyClass`1[System.String]' is invalid because it is neither a built-in type nor implements ILiquidizable
```

However, I've found that if I create a new class that _inherits_ from `MyClass<string>`, it works fine:

```cs
[LiquidSafe]
public class MyStringClass : MyClass<string>
{
}
```

Here's the .NET fiddle demonstrating the working implementation with the non-generic class: https://dotnetfiddle.net/L4wqQw.

And here is the .NET fiddle showing how the generic version blows up on render: https://dotnetfiddle.net/L4wqQw

The generic class worked back when I was using the `LiquidType` attribute. Any ideas on why it's not working with the `Template.RegisterSafeType()` way of registering safe types?

**Comment by microalps** [comment]
Seems like this is no longer an issue as the fiddle is working as expected. Not sure which PR fixed this, but this issue can be closed.
