### ISSUE TITLE
Context.AddFilter() does nothing when rendering a Template

### ISSUE THREAD

**Issue by mjashanks** [dotliquid/dotliquid#295]
### Dotliquid version
Using commit: baaf2a6f4ff0d1cad8ccbdbcb234d49574bb85dd
### Expected behavior
Adding a filter function, via Context.AddFilter, should work when using a Template and a Drop
### Actual behavior
The filter function is not registered, and therefor not used
### Steps to reproduce the Problem (you can add files)

PR #296 demonstrates the issue with a unit test.

**Comment by microalps** [comment]
@mjashanks have you ever resolved this? Please update task and PR if this is all good. It seems to me that the issue with the unit test is that you are setting localVariables to the renderParameters, but context is already created so it doesn't override the context. The below snippet works for me:

```
var context = new Context(CultureInfo.InvariantCulture);
var renderParams = RenderParameters.FromContext(context, context.FormatProvider);
context.Environments.Add( Hash.FromAnonymousObject(data) );
```

**Comment by mjashanks** [comment]
Hey, I haven't revisited this, so am happy for you to close this. Thanks for getting back :)
