### ISSUE TITLE
Basic Filters not working

### ISSUE THREAD

**Issue by yoyos** [dotliquid/dotliquid#298]
### Dotliquid version

DotLiquid" version="2.0.254" targetFramework="net45"

### Expected behavior

{{ 5 | modulo:2 }} should display 1
{{ 5 | times:2 }} should display 10

### Actual behavior

{{ 5 | modulo:2 }} displays 5
{{ 5 | times:2 }} displays 5

### Steps to reproduce the Problem (you can add files)

This is more a question than a bug as I think I'm not seeing something or I didn't enable something to lets the renderer uses math functions.

My customfilters are working fine but not math functions are working. Do you think that enabling customfilters will remove basic ones ?

Do you have an idea what the problem could be ?

Thank you !

**Comment by cmk1988** [comment]
I had the same issue. Try this: 
{{ 5 | Modulo:2 }}
{{ 5 | Times:2 }}
Use upper case for the first character of the filters.

**Comment by daviburg** [comment]
Yes, simple casing issue with the filter token.

**Comment by sheeraz-srz** [comment]
Not all the filters work just with first letter as upper case. For example, divided_by works as DividedBy. 
This can be confirmed by referring DotLiquid.xml file that comes along with the DotLiquid nuget package.
You could download nuget package from https://www.nuget.org/packages/DotLiquid/2.1.457 which will have the xml and all the filters could be found from it.
[DotLiquid.xml.txt](https://github.com/dotliquid/dotliquid/files/6708402/DotLiquid.xml.txt)

**Comment by microalps** [comment]
@sheeraz-srz that is noted in https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Syntax-Compatibility#naming-convention and is actually an option whether you want to use PascalCase or snake_case. The naming in xml comments reflect PascalCase but are not a must.
