### ISSUE TITLE
Drop for Xml Document

### ISSUE THREAD

**Issue by deanebarker** [dotliquid/dotliquid#299]
Has anyone developed a Drop for XML documents?  I whipped one up, but it has limitations, and I'm curious if there's other work that has been done here.

```
<person>
  <name>
    <first>Deane</first>
    <last>Barker</last>
  </name>
</person>
```
This code:
```
var template = Template.Parse(@"

   Hi {{ data.person.name.first }}!

");
var result = template.Render(Hash.FromAnonymousObject(
  new { data = new XmlDrop(myXmlString) }
));
```
What it does it user `BeforeMethod` to try and find an XML node with text in it (a `text()` node in XPath).

* If it finds one, it returns the text of it.
* If not, it uses the node it _did_ find to extract the inner XML and return a new XmlDrop object.

So the template above actually drills down through three XmlDrop objects before finding one with text. It "lifts out" the inner XML each time, progressively creating a smaller snippet of XML for a new XmlDrop.

There are limitations, primarily caused by the fact that when I find a node, the only way I know if it's what the user wanted is if it has inner text. This means that the drilldown stops there, even if there are child elements or attributes the user might want. I think this is surmountable with a little more thought.

But, this is 10 minutes worth of work. I don't want to take it further if someone else has done something amazing.

**Comment by darrelmiller** [comment]
We implemented something similar but it seems we took a different approach.  We implemented Indexable on the drop and walk down the path either creating a new drop if there are child elements or returning the element value if we run out of path.

I would love to find a way of addressing attributes also, but my efforts so far have always had something that didn't work.

**Comment by deanebarker** [comment]
We did this:

    <person>
      <name type="full">Deane Barker</name>
    </person>

    {{ data.name.attr-type }}

So the `attr` prefix is detected, stripped off, and the value of the `type` attribute is returned.

**Comment by darrelmiller** [comment]
@deanebarker Sneaky.  I like it.

**Comment by deanebarker** [comment]
Here is ours:

https://gist.github.com/deanebarker/408970e5cc2ebd3597a4d87a1cadc672

**Comment by darrelmiller** [comment]
Holy crap.  I didn't even know about the notion of a method.  That opens up a whole slew of possibilities.  We just mapped the dotted segments of the binding path to element names by walking down the XElement DOM.  We ignored case and ignored namespaces.  Which introduces a whole new set of challenges.

**Comment by deanebarker** [comment]
What sucks is that you can't get the entire "method chain" at once. You can only get the methods one at a time. I have #300 open on this right now, but no answers yet.

(FYI: I just found and corrected a bug in that code...)

**Comment by icnocop** [comment]
I'm thinking a better approach would be to just deserialize the XML to an object.

```
        [TestMethod]
        public void TestMethod1()
        {
            string xmlString = @"
                <person>
                    <name>
                        <first>Deane</first>
                        <last>Barker</last>
                    </name>
                </person>";

            XmlSerializer serializer = new XmlSerializer(typeof(Person));
            using (TextReader reader = new StringReader(xmlString))
            {
                Person person = (Person)serializer.Deserialize(reader);
                PersonDrop drop = new PersonDrop
                {
                    Name = new NameDrop
                    {
                        First = person.Name.First,
                        Last = person.Name.Last
                    }
                };

                var template = Template.Parse(@"
                   Hi {{ person.name.first }}!
                ");

                Hash hash = Hash.FromAnonymousObject(new { Person = drop });

                string result = template.Render(hash);

                Assert.AreEqual("Hi Deane!", result.Trim());
            }
        }
```
```
    public class PersonDrop : Drop
    {
        public NameDrop Name { get; set; }
    }

    public class NameDrop : Drop
    {
        public string First { get; set; }

        public string Last { get; set; }
    }

    [XmlRoot("person")]
    public class Person
    {
        [XmlElement("name")]
        public Name Name { get; set; }
    }

    public class Name
    {
        [XmlElement("first")]
        public string First { get; set; }

        [XmlElement("last")]
        public string Last { get; set; }
    }
```

**Comment by icnocop** [comment]
I found a better solution which makes use of `ExpandoObject`.

```
XDocument doc = XDocument.Parse(xmlData);
var builder = new StringBuilder();
JsonSerializer.Create().Serialize(new CustomJsonWriter(new StringWriter(builder)), doc);
var jsonText = builder.ToString();
dynamic root = JsonConvert.DeserializeObject<ExpandoObject>(jsonText);
Hash hash = Hash.FromDictionary(root);
string result = template.Render(hash);
```

Sources:
https://stackoverflow.com/a/39902334/90287
https://stackoverflow.com/a/43485727/90287

**Comment by deanebarker** [comment]
> I'm thinking a better approach would be to just deserialize the XML to an object.

Yes, but in my use case, I was specifically trying to avoid having a typed object for it. I wanted to "wrap" generic HTML in a single object (Drop), without having to have a C# object representation for every different type of XML.

Put another way, at compile time, I had no idea what XML I was going to template at runtime.

**Comment by deanebarker** [comment]
> I found a better solution which makes use of `ExpandoObject`.

I did this too, and here's the thing: I found a problem with it, but I can't remember what it was. Seriously. I hate it when this happens, but I went down the same road and there was some roadblock at the end which made me look for a different solution.

**Comment by icnocop** [comment]
Here are a couple more ideas but I haven't tried using them:
https://stackoverflow.com/q/12240426/90287

1. Use `ElasticObject`.
Source: https://stackoverflow.com/a/12240510/90287

2. Inherit from `DynamicObject` and override `TryGetMember`.
https://stackoverflow.com/a/15994600/90287

**Comment by microalps** [comment]
This issue can be closed as there are several approaches listed here to choose from.
