### ISSUE TITLE
Is it possible for a Drop to gain knowledge of the entire method "chain" at once?

### ISSUE THREAD

**Issue by deanebarker** [dotliquid/dotliquid#300]
Is it possible to get the entire "method string" for an object at once?  Consider this:

    {{ foo.bar.baz }}

If `foo` is a Drop then the `BeforeMethod` override will just get `bar`. It will return a Drop, which will then get `baz`. Neither execution of `BeforeMethod` will have any knowledge of the other.

Is there any way for `foo` to get `bar.baz` together, in `BeforeMethod` or by some other method?

I could make `foo` an `IIndexable` and do this...

    {{ foo['bar.baz'] }}

...but I don't love the syntax. I'd much rather use the other syntax, if possible.

**Comment by deanebarker** [comment]
Alternately, is there any way for `BeforeMethod` to know if it's the last invocation in that chain?

Because, I can do this:

```
public FooDrop : Drop
{
   private List<string> methodChain = new List<string>();

   public override object BeforeMethod(string method)
   {
       methodChain.Add(method);
       if(isLastMethod())  // This is the thing I need...
       {
           var chain = string.Join(".", methodChain);
           // Do amazing things here
       }
       else
       {
          return this;
       }
    }
}
```

**Comment by microalps** [comment]
This is not possible at this time. If there is an equivalent feature in Ruby Liquid, please point it out so it can be evaluated for inclusion. Also, I will note the second approach would not be thread safe and thus wouldn't make sense to build. Feel free to either reopen with references to Ruby or if you are willing to create a PR and have ideas to discuss.
