### ISSUE TITLE
Using variables inside tags?

### ISSUE THREAD

**Issue by kanertuncel** [dotliquid/dotliquid#304]
Hi,
Is there any option to use variables inside tags like,

`{% for product in category.products | limit: {{section.limit}} %}`

I've tried using capture or assign didn't work for me.
Thanks in advance..

**Comment by cmk1988** [comment]
Try  "| **L**imit:"

**Comment by chriswatsonaus** [comment]
You shouldn't need the {{}} braces inside the tag.

**Comment by microalps** [comment]
@kanertuncel is this resolved? If not, please let us know. We will close this ticket in 7 days if we don't hear otherwise.
