### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by HybridSolutions** [dotliquid/dotliquid#307]
Does anyone know what is the latest "stable" version of dotliquid? It's 1.7 from the downloads page, 1.8 from CHANGELOG or 2.0.262 from Nuget?

**Comment by hmadrigal** [comment]
Hi,

From its page  http://dotliquidmarkup.org the download section says; DotLiquid v1.7.0
which I think it's not maintained, and now nuget.org has the latest version https://www.nuget.org/packages/DotLiquid/  v2.0.262 (published 2 months ago).

Not sure if they have a different package for DotNetCore thus, it may have a different version number. 
In my repo, my examples are likely to be using an old version.

**Comment by microalps** [comment]
Will accept a PR to remove a link to downloads from the README and update ChangeLog to note that 2.0 onwards is not maintained outside of git commits. 

The current version, to answer the Q, is 2.1.405
