### ISSUE TITLE
Let me use a POCO

### ISSUE THREAD

**Issue by oliverjanik** [dotliquid/dotliquid#308]
### Dotliquid version
All

### Expected behavior
Render works with POCO

### Actual behavior
Render does not work with POCO. Compilation error.

### Steps to reproduce the Problem (you can add files)
```
            var t = Template.Parse(template);
            t.Render(myPoco);
```

I find the safety reasoning very very weak. Let me use a damn POCO. We're all adults here. Every responsible programmer will have a DTO just for the template.

**Comment by SimonGates** [comment]
Have you tried this?
https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Drops#poco-classes

**Comment by oliverjanik** [comment]
That thing links to https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Developers which does not mention anything about POCOs.

I abandoned this lib. Too much ceremony. Looks like Ruby written in C#.

**Comment by microalps** [comment]
As the documentation explains,  there are many ways to identify safe types and or properties. Since this library is based on its ruby counterpart, this core requirement is expected by all those familiar with Liquid Syntax. Closing issue.
