### ISSUE TITLE
DateTimeOffset not supported?

### ISSUE THREAD

**Issue by oliverjanik** [dotliquid/dotliquid#309]
### Dotliquid version
2.0.266

### Expected behavior
Some sort of output.

### Actual behavior
Empty string

### Steps to reproduce the Problem (you can add files)
```
        [Fact]
        public void CanRenderPoco()
        {
            var userCtx = new UserContext { Name = "Oliver", CreatedAt = new DateTimeOffset(2018, 7, 4, 15, 6, 41, TimeSpan.FromHours(10))};
            var t = Template.Parse("Hi {{name}}! You were created at {{createdAt}}");

            var result = t.Render(Hash.FromAnonymousObject(userCtx));

            Assert.Equal("Hi Oliver! You were created at xyz", result);
        }
```

```
Xunit.Sdk.EqualException
Assert.Equal() Failure
                                 ↓ (pos 31)
Expected: ···You were created at xyz
Actual:   ···You were created at 

```

**Comment by laedit** [comment]
As stated in the wiki, DotLiquid follow Liquid convention by default for variable names, have you tried with `{{created_at}}` instead?
If you want to use `CreatedAt`, you have to set `Template.NamingConvention` to `new NamingConventions.CSharpNamingConvention()`.
