### ISSUE TITLE
Template.Render doesn't replace tags inside tag recursively

### ISSUE THREAD

**Issue by jasonycw** [dotliquid/dotliquid#319]
### Dotliquid version
2.0.298.0

### Expected behavior
Replace tag inside the tag

### Actual behavior
Only replace the tag once, not recursively

### Steps to reproduce the Problem
import file
> {{something}}
> {{somethingElse}}

![image](https://user-images.githubusercontent.com/4518597/45210067-34426980-b2c1-11e8-9e8f-e3c8c6123411.png)

Result:
> First something and something {{somethingElse}}
> SOMETHING ELSE

I was hoping for 
> First something and something SOMETHING ELSE
> SOMETHING ELSE

**Comment by microalps** [comment]
The method render is intender to render while you are trying to use it to parse. You might be able to achieve this using a custom IFileSystem but it would be hack and not what this library is for.
