### ISSUE TITLE
Iterating over Nested Dictionary in For Loop

### ISSUE THREAD

**Issue by danielcrabtree** [dotliquid/dotliquid#320]
It is not possible to loop over the elements of a nested dictionary using a for loop.

For example, this does not work:
```
var dictionary = new Dictionary<string, object> {{
    "People", new Dictionary<string, object> {
        { "ID1", "Jane" },
        { "ID2", "Mike" }
    }
}};

// This currently outputs empty string "" instead of "JaneMike"
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value }}{%endfor%}", Hash.FromDictionary(dictionary));
```

The issue appears to have been caused by the PR for #157.

In my example above, we have a dictionary containing a dictionary containing string values - 2 levels of dictionary.

In #157, there is a dictionary containing a dictionary containing a dictionary containing string values - 3 levels of dictionary.

The PR for #157 added code that intercepts values where the 2nd level is a dictionary, but then only outputs values when the 3rd level is also a dictionary. When the 3rd level is not a dictionary, as in my example where it is a string, it doesn't set anything in the context (since value is Hash is false in BuildContext).

It is possible that nested dictionaries were not supported properly at the time of #157, but simply removing the code added for #157 now resolves all these issues.

There is also the issue that #157 had a bug in it's test case:
```
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.First }}{%endfor%}", Hash.FromDictionary(dictionary));
```

This test case just ignores the 2nd level entirely and dots into the 3rd level. You wouldn't expect that when iterating over the 2nd level dictionary.

Instead, the test for #157 should have been:
```
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value.First }}{%endfor%}", Hash.FromDictionary(dictionary));
```

Here you are explicitly stepping through the 2nd level. It is possible that #157 was never an issue and the original writer was just unaware of .Value or perhaps .Value was not supported at that time.

I have submitted a PR which fixes this issue. It also adds 2 new tests and updates the third. 

One new test is for my example, the 2nd level dictionary. 
The other new test shows how you can substitute a list for the dictionary at the 2nd level to keep the direct item.First access desired in #157.
The updated test fixes the original test for #157 to step through the 2nd level dictionary using .Value.

**Comment by microalps** [comment]
@daviburg What are your thoughts here? Is this still an issue (I didnt test) and are there any reservations to fixing this?
