### ISSUE TITLE
Updating from 1.8

### ISSUE THREAD

**Issue by rwb196884** [dotliquid/dotliquid#323]
### Dotliquid version
Running code built against version 1.8.

Switched NuGet package to 2.0.298.0 and added binding redirect.

### Expected behavior
All works as before.

### Actual behavior
System.MissingMethodException: 'Method not found: 'DotLiquid.Hash DotLiquid.Hash.FromAnonymousObject(System.Object)'.'

Also seeing MissingFieldException to do with DotLiquid.Template.NamingConvention.

Any pointers on how to fix?

**Comment by rwb196884** [comment]
I guess this used to be the method.
https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/Hash.cs#L33

Here is the breaking change.
https://github.com/dotliquid/dotliquid/blob/8c267794399571d048df0aa7d3581e6d32799712/src/DotLiquid/Hash.cs

**Comment by microalps** [comment]
It seems like a recompile would be expected when changing major versions. Closing this issue.
