### ISSUE TITLE
DotLiquid.Tag.If with one statement doesn't add error VariableNotFoundException

### ISSUE THREAD

**Issue by chs2000** [dotliquid/dotliquid#326]
### Dotliquid version 
2.0.298

### Expected behavior
 Add Exception VariableNotFoundException in to Errors Collection

### Actual behavior
Exception VariableNotFoundException is not added in to Errors Collection

### Steps to reproduce the Problem (you can add files)
Run this code
```
            Template template = Template.Parse("{% if isTestWrongName %}TEST{% endif %}"); // Parses and compiles the template
            template.Render(Hash.FromAnonymousObject(new { isTest = true }));
            Console.WriteLine(template.Errors.Count);
```

I take a look on Dotliquid code  in class Condition.cs 
and see next
```
            if (string.IsNullOrEmpty(op))
            {
                object result = context[left, false];
                return (result != null && (!(result is bool) || (bool) result));
            }

```
so variable notifyNotFound is false and I cannot to find that my template is broken
Can you fix this problem (or add some setting that I can manage it)

**Comment by microalps** [comment]
Similar issue to #265 , closing and linking the two.
