### ISSUE TITLE
Items appearing empty

### ISSUE THREAD

**Issue by Marvin-Brouwer** [dotliquid/dotliquid#327]
### Dotliquid version
2.0.298
### Expected behavior
I have a linq grouping I want to generate into an email like this (this is just with stringbuilder):
![2018-11-19_1650](https://user-images.githubusercontent.com/5499778/48719011-c7324500-ec1c-11e8-9185-03784c5af562.png)
### Actual behavior
However the outcome looks like this:
![2018-11-19_1649](https://user-images.githubusercontent.com/5499778/48719017-cb5e6280-ec1c-11e8-83f3-623f30c163c3.png)
It recognizes the items but doesn't output their values.
### Steps to reproduce the Problem (you can add files)
I've added the types to the safe types:
![2018-11-19_1651](https://user-images.githubusercontent.com/5499778/48719289-69eac380-ec1d-11e8-825a-880972b29af6.png)

This is the code I use:
```

            var path = Path.Combine(executionDirectory, "MailMessage", "Report.xml");
            var file = new FileInfo(path);
            using (var reader = file.OpenText())
                _mailTemplate = Template.Parse(reader.ReadToEnd());

            var reportLinesByType = reportLines
                .GroupBy(report => report.Item.ReportType);

            var test = _mailTemplate.Render(Hash.FromAnonymousObject(new { title, reportLinesByType })); // Renders the output => "hi tobi"
```

```
<body>
    
    <h1>{{ title }}</h1>

    {% for reportTypeGroup in reportLinesByType -%}
        <h2>{{ reportTypeGroup.Key }}</h2>
        <ol>
            {% for reportLine in reportTypeGroup -%}
                <li>{{ reportLine.Message }}</li>
            {% endfor -%}
        </ol>
    {% endfor -%}
    
</body>
```

**Comment by microalps** [comment]
Was this issue resolved? It seems like you are passing IQueryable to your anonymous type.  You might want to use .Select to build a new anonymous type with group/subitems and .ToList to compute and return objects. Please provide an update so we can close this issue.

**Comment by Marvin-Brouwer** [comment]
Hi, I don't think I ever bothered fixing this because it's only the source and the email looks fine.
I won't be able to look at this for at least a month, I'll get back to you after that

**Comment by Marvin-Brouwer** [comment]
Hi, I am terribly sorry but I'm still swamped.
I've had a look at my emails for this project but I can only see exception mails which look fine.
Since it was an R&D project anyway I've stopped the servers on my MSDN subscription so it's going to take a bit more time to re-test this than just updating a library.

I'm happy to keep pushing this forward until I do have time but I realize that might not be acceptable for you.
So I'm also fine if we just close this issue.

**Comment by microalps** [comment]
It's been several months since the last response. Feel free to reopen if you have more details to share.
