### ISSUE TITLE
Date with minus filter. Parameter count mismatch

### ISSUE THREAD

**Issue by MattHartz** [dotliquid/dotliquid#328]
### Dotliquid version
2.0.298

### Expected behavior
C# Code
`
DotLiquid.Template template = DotLiquid.Template.Parse(email.Body);
Liquid.UseRubyDateFormat = true;
Template.NamingConvention = new DotLiquid.NamingConventions.RubyNamingConvention();
var htmlContent = template.Render(DotLiquid.Hash.FromAnonymousObject(emailData));
`
HTML
` {% assign date_start = activity.created_on | date: "%s" %} ` returns something like 1542645650
`{% assign date_start = activity.created_on | date: "%s" | minus : 604800 %}` return 
1542645650 - 604800
### Actual behavior
` {% assign date_start = activity.created_on | date: "%s" %} ` returns something like 1542645650
`{% assign date_start = activity.created_on | date: "%s" | minus : 604800 %}` Gives me "Liquid error: Parameter count mismatch."

**Comment by nichojo89** [comment]
This issue is still present in 2020. I may have to ditch my whole implementation now. When using **M**inus in a liquid template for an azure logic app we get this error. minus doesnt even work in azure logic apps.
