### ISSUE TITLE
Can't find sources for version 2.0.298

### ISSUE THREAD

**Issue by rhegner** [dotliquid/dotliquid#329]
### Dotliquid version

2.0.298

### Expected behavior

I can find sources tagged with a v2.0.298 label in this repository.

### Actual behavior

The newest tag I find in this repository is v1.6.1

### Context

This issue is somewhat related to #307. I'd like to see the sources for version 2.0.298 but there seems to be a discrepancy between the versions on Nuget and the versions in this repository. Has active development of this library moved to some other repository? If not, could you please point me to the commit which represents v2.0.298?

**Comment by microalps** [comment]
Builds are automated by AppVeyor and pushed to nuget. Git tags are not updated, but you can find all build and a link to the commit at https://ci.appveyor.com/project/tgjones/dotliquid/history
To spare you having to scroll, here it is https://github.com/dotliquid/dotliquid/commit/834056284456c9b4e3ee90020f3afbfaceb3278a

**Comment by microalps** [comment]
@daviburg please close.
