### ISSUE TITLE
Missing Standard filters: Ceil, Concat, EscapeOnce, Floor, SortNatural

### ISSUE THREAD

**Issue by mj-fox** [dotliquid/dotliquid#330]
### Dotliquid version
2.0.180.0
### Expected behavior
The Liquid filters Ceil, Concat, EscapeOnce, Floor, SortNatural to be working in DotLiquid.
### Actual behavior
Filters not working because not implemented yet.

The Original Liquid's set of standard filters also include the above mentioned. Although most people probably don't need filters like Concat or SortNatural, Ceil and Floor are basic functions available in many template languages.

**Comment by cdwiegand** [comment]
Submitted pull request to add ceil and floor filters: https://github.com/dotliquid/dotliquid/pull/399

**Comment by microalps** [comment]
@daviburg  PR #399 was merged, please close

**Comment by daviburg** [comment]
PR 399 is not enough. This issue also notes additional missing filters besides Ceil and Floor.

**Comment by microalps** [comment]
Liquid 5.0 introduces echo and liquid tags. These are also a gap in DotLiquid now.

**Comment by microalps** [comment]
As the only remaining filter has its own issue report, this can be closed.
