### ISSUE TITLE
Attribute passing on the "include" tag is broken

### ISSUE THREAD

**Issue by deanebarker** [dotliquid/dotliquid#332]
### Dotliquid version

2.02.298

### Expected behavior

This template code should make the "outer" value of `title` available in the included template as the variable `partial_title`:

```
{% include _mypartial partial_title=title %}
```

### Actual behavior

It does not work. `partial_title` is empty in the include template, and I've found the offending line here:

https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/Tags/Include.cs#L29

```
R.Scan(markup, Liquid.TagAttributes, (key, value) => _attributes[key] = value);
```

That line just doesn't find attributes. The `_attributes` dictionary remains empty after it executes.

For giggles, I manually added the attribute right under that line.

```
_attributes.Add("partial_title", "title");
```

It worked as expected, so it's a _parsing_ problem, clearly.

### Steps to reproduce the Problem (you can add files)

See code above. Run the template code under "Expected Behavior." The `partial_title` variable will be empty in the partial.

**Comment by deanebarker** [comment]
I verified this line of code isn't working by rigging up a test:

```
var markup = "name=Deane mood=Frustrated";
R.Scan(markup, Liquid.TagAttributes, (key, value) => Console.WriteLine(key + ":" + value));
```

Nothing is output.

**Comment by deanebarker** [comment]
I don't know what to say except that the regex pattern in `Liquid.TagAttributes` is...broken?  Can this be?

I isolated this probably down to the `Regex.Match` call inside `R.Scan`. The regex pattern just doesn't detect anything.

I swapped it out for:

```
(\S+)=["']?((?:.(?!["']?\s+(?:\S+)=|[>"']))+.)["']?
```

This successfully populated the `_attributes` collection.

I refuse to believe this is broken and no one noticed. What am I doing wrong here?

**Comment by VaclavElias** [comment]
I was testing this with v3 and it is working with this syntax, not the ```:``` instead of ```=```.

```{% include _mypartial partial_title: title %}```

**Comment by microalps** [comment]
It would seem this is the correct syntax, looking at the current documentation for render (that replaces include in the Ruby liquid syntax). Closing this task as resolved thanks to @VaclavElias 

Ref: https://shopify.github.io/liquid/tags/template/#render
