### ISSUE TITLE
Hash.FromAnonymousObject doens't work on class hierarchies

### ISSUE THREAD

**Issue by rwb196884** [dotliquid/dotliquid#336]
### Dotliquid version
2.0.298

### Expected behavior
`Hash.FromAnonymousObject(thing, true)` has a key for every property of every class in the class heirarchy of `thing`.

### Actual behavior
`Hash.FromAnonymousObject(thing, true)` only has a key for every property of the type of  `thing` and its immediate base class; properties of the base class of the base class (etc.) of `thing` are omitted.

### Steps to reproduce the Problem (you can add files)
```
    public class Bottom
    {
        public string BottomValue { get; set; }

        public object ToLiquid() => Hash.FromAnonymousObject(this, true);
    }

    public class Middle : Bottom
    {
        public string MiddleValue { get; set; }
    }

    public class Top : Middle
    {
        public string TopValue { get; set; }
    }

    [TestFixture]
    public class TestLiquidInheritance : UKPlc.UnitTest.SetUpFixture
    {
        [TestCase]
        public void TestRenderInheritance()
        {
            Top t = new Top()
            {
                BottomValue = "Bottom",
                MiddleValue = "Middle",
                TopValue = "Top"
            };

            Hash h = (Hash)t.ToLiquid();
            Assert.AreEqual(h.Keys.Count, 3); // Fails because Bottom is omitted.            
        }
    }
```

**Comment by rwb196884** [comment]
Hello?
Anyone give a fuck?

**Comment by microalps** [comment]
@rwb196884 Care to clean up your two PRs into a single PR for review? Also, there is no test for child class overriding base class object with same name (although code seems to have that)

**Comment by rwb196884** [comment]
I don't know how so you'll have to take them or leave them.
