### ISSUE TITLE
Dynamic inlcudes do not seem to work.

### ISSUE THREAD

**Issue by groogiam** [dotliquid/dotliquid#340]
### Dotliquid version
Version 2.0.298
I am trying to set the template name of an include directive as a variable. This looks like it is supported in some versions of liquid based on the following article.

https://stackoverflow.com/questions/23541185/jekyll-liquid-include-files-dynamically

However dotliquid always uses the string literal and does not evaluate the variable for the template name.
The following statement should evaluate the value of HeaderTemplateName but instead just passes the actual string literal to the FileSystem provider.

{% include "{{ HeaderTemplateName }}" %}

**Comment by microalps** [comment]
We are using this all the time - `{% assign LayoutName = Whatever.LayoutName %}{% include LayoutName %}`. Incidentally, someone posted that on your referenced SO question https://stackoverflow.com/a/61525134
