### ISSUE TITLE
default tag should accept non-string values

### ISSUE THREAD

**Issue by PatrickNausha** [dotliquid/dotliquid#341]
### Expected behavior
`{{ this_is_not_defined | default: 2.9 }}` should emit `2.9` into the rendered document when `this_is_not_defined` is not defined or is `nil`.

### Actual behavior
Instead I get `Liquid error: Object of type 'System.Single' cannot be converted to type 'System.String'.`

### Details
[The first example](https://shopify.github.io/liquid/filters/default/) in the Shopify liquid docs for `default` uses a number as the default value: `{{ product_price | default: 2.99 }}`

It looks like [the source for `Default`](https://github.com/dotliquid/dotliquid/blob/834056284456c9b4e3ee90020f3afbfaceb3278a/src/DotLiquid/StandardFilters.cs#L658-L661) does not attempt to handle non-string values.

`{{ this_is_not_defined | default: "2.9" }}` works as expected and emits `"2.9"`.

**Comment by microalps** [comment]
@daviburg  This cannot be reproduced in the current version. Confirmed this was fixed by 0e98de5f5eed5ec3e7326435da41a8859895d43e. Please close this issue.
