### ISSUE TITLE
Override ToLiquid() in Template.RegisterSafeType()

### ISSUE THREAD

**Issue by watkinsmatthewp** [dotliquid/dotliquid#345]
### Dotliquid version

Any

### Description

I'm using reflection to register some types and members from a third-party library using `Template.RegisterSafeType()`. So far so good. But a lot of these object types have a `name` property. For brevity's sake, I would like to be able to print the object's `Name` whenever I don't reference a different property.

For example, suppose the `Dog` object has properties `Name` and `Breed`. Suppose the `Car` object has properties `Name` and `Model`. Right now my liquid has to call name explicitly:

```liquid
My {{ car.model }}'s name is {{ car.name }} and my {{ dog.breed }}'s name is {{ dog.name }}
```

I want liquid to emit the name by default, so that I can write:

```liquid
My {{ car.model }}'s name is {{ car }} and my {{ dog.breed }}'s name is {{ dog }}
```

I know that if the classes implemented `ILiquidizable`, I could just specify that in the `ToLiquid` method:

```cs
public object ToLiquid() => Name;
```

But like I said, these types are defined in a third-party component, which is why I'm registering them using `Template.RegisterSafeType()` in the first place.

Is there any way to specify the `ToLiquid` behavior when registering a type manually? Something like:

```cs
static object ToLiquid(Type type, object instance) => type.GetProperty("Name")?.GetValue(instance)?? instance;

void DoWork()
{
  Template.RegisterSafeType(typeof(Dog), new[] { "Name", "Breed" }, ToLiquid);
}
```

Is there any way to do this at runtime like that?

**Comment by microalps** [comment]
Have you tried
```
Template.RegisterSafeType(typeof(Dog), new[] { "Name", "Breed" }, (instance) => typeof(Dog).GetProperty("Name")?.GetValue(instance) ?? instance);
```

**Comment by watkinsmatthewp** [comment]
Been three years since I asked this question and I'm working in a different company now. :)
