### ISSUE TITLE
DotLiquid - Array filters should support 'where' filter clause

### ISSUE THREAD

**Issue by praveensri** [dotliquid/dotliquid#347]
### Dotliquid version
Latest Dot Liquid
### Expected behavior
'where' filter should work
### Actual behavior
'where' clause is not working
### Steps to reproduce the Problem (you can add files)

The original Liquid project supports 'where' clause 
https://help.shopify.com/en/themes/liquid/filters/array-filters#where

**Comment by jonorossi** [comment]
DotLiquid doesn't have the where filter, along with some of the other newer filters added to Liquid: https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/StandardFilters.cs

I'd suggest writing your own custom where filter to live in your own codebase, then contributing it to this project when it is stable.
