### ISSUE TITLE
Filters do not utilize culture set for rendered parameters

### ISSUE THREAD

**Issue by anato-s** [dotliquid/dotliquid#349]
**Dotliquid version** 
dll v2.0.3.314.0; nuget package v2.0.314 

**Expected behavior** 
Code
```c#
var templTxt = "{{ExtendedProps.Key2|Currency}}"

var model = new CompositeModel()
{
    ExtendedProps = new Dictionary<string, object>() { { "Key2", 22.33 } } 
};
Hash hash = Hash.FromAnonymousObject(model);
var rendParams = new RenderParameters(CultureInfo.GetCultureInfo("fr-Fr"))
{
    LocalVariables = hash,
    ErrorsOutputMode = ErrorsOutputMode.Suppress
};
string output = templ.Render(rendParams);`
```

When I run the code, I expect output like below, because I set culture info for the entire job
>29/8/2019 18:17:04 22.33 €

Instead I get
>8/29/2019 6:17:04 PM $22.33

And yes, without filter I get it rendered correctly but not in specific format.
It seems that culture info should be propagated to filters. I know that I can set filter as `{{ExtendedProps.Key2|Currency:"fr-Fr"}}` but this is not super good. Because the real issue is that I want to write custom filters and have culture info available for them. Can custom filter become `IContextAware`? Thanks

**Comment by anato-s** [comment]
At first I thought to close it because I found the way - create custom filter with signature `filter(context, object)` and inside use `ToString.("C", context.FormatProvider)`. But then I thought, why this is not implemented by a standard `Currency` filter?

**Comment by sebastienros** [comment]
Is currency actually standard or something that Shopify is adding?

**Comment by anato-s** [comment]
@sebastienros  There is a standard filter "Currency" there in DotLiquid. In the file StandardFilters. I don't even know what is Shopify. I use it in custom .net development

**Comment by microalps** [comment]
Not in docs or https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb - I'd approve a PR to change.

**Comment by microalps** [comment]
Not in docs or https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb - I'd approve a PR to change. Looks like numerous filters likewise use CurrentCulture imstead of the context's culture.

**Comment by skalahonza** [comment]
Any update on this? I am still hitting this issue.

**Comment by microalps** [comment]
@skalahonza  can you provide more details which filter you are hitting this with so someone can focus on a fix? Are you willing to make a PR?

**Comment by skalahonza** [comment]
I will prepare a code sample. Yes I can make a PR.
