### ISSUE TITLE
How add custom tag with params ?

### ISSUE THREAD

**Issue by hakob8956** [dotliquid/dotliquid#357]
### Dotliquid version
2.0.314
### Expected behavior
I can't create a tag with params
 for example data:"%d" ->date is tag and %d parametr

**Comment by microalps** [comment]
Duplicate of #356 @daviburg please close

**Comment by daviburg** [comment]
This one is slightly better formatted, keeping it and closed the other.

**Comment by microalps** [comment]
See the wiki - https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Developers#create-your-own-tags 

As far as parsing the markup for params, that is not dictated by the library and can be coded within the `Initialize` method.
