### ISSUE TITLE
Feature Request: Add a BeforeMethodAsync to Drop

### ISSUE THREAD

**Issue by k290** [dotliquid/dotliquid#358]
### Dotliquid version
2.0.314
 
Since async programming is much more common practise, can you please provide an asynchronous version of BeforeMethod to the Drop?

Yes you can do things like Task.FromResult inside. But calling sync from async is littered with potential deadlock issues for the inexperienced developer and is generally an antipattern

**Comment by microalps** [comment]
Async functionality,  as implemented in #354 , has beenmoved to another fork. Closing as library is not async.

**Comment by k290** [comment]
@microalps  can you please link to the fork?
