### ISSUE TITLE
Object properties iteration not working 

### ISSUE THREAD

**Issue by rkg823** [dotliquid/dotliquid#361]
object properties iteration is not working. 
Example template -
[{% for product in items %}{   
  {% for prop in product %}
  test-{{ prop[0] }}: {{prop[1]}}
  {% if forloop.last == false%}, {% endif %}
  {% endfor %}
}{% if forloop.last == false%}, {% endif %}{% endfor %}]

**Comment by microalps** [comment]
Kindly provide more details on the issue. What is the data model? What is a 'prop' - are you expecting to iterate properties with reflection??? Please provide more info or we will close this issue in 7 days.

**Comment by rkg823** [comment]
the data model is as following -
items = [ {prop1: value1, prop2: value2}]
I need to itterate each object proprties as below 
[{% for product in items %}{
{% for prop in product %}
{{ prop.key }}: {{prop.value}}

**Comment by microalps** [comment]
Is that a class with prop1 and prop2? A dictionary? Dynamic? Some .net code will be helpful

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.
