### ISSUE TITLE
Access property name with dot

### ISSUE THREAD

**Issue by rkg823** [dotliquid/dotliquid#363]
HI, I have scinario where i need to access json property name with dot. for a example 
json - { "dot.propety": "some value"} - 
how can i access ['dot.property'] from the josn ?

**Comment by microalps** [comment]
Same issue was posted by the same person to https://github.com/Shopify/liquid/issues/1232 - is this a real issue?

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.
