### ISSUE TITLE
Object extension methods to take into account Drops that overwrite the indexer to get their values

### ISSUE THREAD

**Issue by jmalarcon** [dotliquid/dotliquid#364]
### Dotliquid version
2.0.325

### Expected behavior
The `RespondTo` and `Send` methods in `DotLiquid.Util.ObjectExtensionMethods` return indexed properties in Drops that overwrite the indexer to get values.

### Actual behavior
They only return values from real properties in the Drop.

### Steps to reproduce the Problem (you can add files)
With the current implementation of the `RespondTo` and `Send` methods in `DotLiquid.Util.ObjectExtensionMethods`, if you have a `Drop` derived class that overrides the indexer in `DropBase` so that it can return arbitrary properties (such as those defined in the Front-Matter of a file), the current methods aren't able to deal with them. **This prevents being able to sort using those arbitrary properties with the sort filter**.

This is a sample code that defines a Markdown class derived from Drop to get some simple properties from a name, overwriting the default indexer. In a real case it would read the properties, for example, from the file's Front-Matter, but to check the issue is enough. DotLiquid is not able to read the properties with the `RespondTo` and `Send` methods.

```csharp
using System;
using System.Linq;
using System.IO;
using DotLiquid;

namespace TestSort
{
    class Program
    {
        static void Main(string[] args)
        {
            DirectoryInfo di = new DirectoryInfo(@"C:\TestFiles\");
            var allFiles = (from file in di.EnumerateFiles("*.md", SearchOption.TopDirectoryOnly)
                            select new MarkdownFile(file.Name, file.Length)
                           );
            Template parser = Template.Parse(@"
{% assign sorted = allFiles | sort: 'length' %}
{% for file in sorted %}
- {{file.Name}}
{% endfor %}");
            Hash context = new Hash(allFiles);
            string res = parser.Render(context);
            Console.WriteLine(res);
            Console.ReadLine();
        }
    }

    //A sample Drop overriding the indexer from the base class
    public class MarkdownFile : Drop
    {
        private string fullName;
        private long length;

        public MarkdownFile(string fullName, long length)
        {
            this.fullName = fullName;
            this.length = length;
        }

        public override object this[object fieldName]
        {
            get
            {
                //Tries to return a real property form the object if present
                object res = base[fieldName];
                if (res == null)
                {
                    switch (fieldName.ToString().ToLowerInvariant())
                    {
                        case "name":
                            res = fullName.ToLowerInvariant();
                            break;
                        case "length":
                            res = length;
                            break;
                        default:
                            res = "";
                            break;
                    }
                }

                return res;
            }
        }
    }
}
```

## Proposed Fix

I opened [a Pull Request](https://github.com/dotliquid/dotliquid/pull/348) #348 , with a fix 5 or 6 months ago. Since nobody answered here or in Gitter I decided to go by myself with my own fork and a different assembly name that now is preventing the PR to be merged.

If you find the fix [in this commit](https://github.com/dotliquid/dotliquid/pull/348/commits/bdf09f20af9f63b4dc8c8aa0268ec27df93c6896) useful and want it to be merged, I can happily create a new PR without the assembly name modifications so that it can be added to the product.

Thanks!

**Comment by microalps** [comment]
Care to provide a use case? Since this is inheriting the Drop class it is expected to be designed for DotLiquid and not vice versa. For sake of discussion, would it be better to inherit IIndexable, ILiquidizable (which tests indicate are supported)?

**Comment by microalps** [comment]
@daviburg I know you discussed in the PR, care to comment?

**Comment by daviburg** [comment]
> @daviburg I know you discussed in the PR, care to comment?

PR should be revised to use IIndexable contract rather than DropBase, then seems pretty ok to me to accept.

**Comment by daviburg** [comment]
Also wondering, isn't there an out of the box interface in C# for an array operator contract? Feels so basic, maybe part of Linq, maybe that's an angle of enumerable.

**Comment by daviburg** [comment]
Is IIndexable a cheapo take on IList?

**Comment by microalps** [comment]
If it's a drop inherited class, then it could implement BeforeMethod which is a catch-all as far as I am reading. I'm not seeing the need for code change to achieve the above. Will give the author 7 days to respond before closing this issue and related PR.

**Comment by microalps** [comment]
> Is IIndexable a cheapo take on IList?

More like a cheapo take on IDictionary. (Also SortedList has this[object key] and ContainsKey methods.)

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.
