### ISSUE TITLE
How to call a method with arguments?

### ISSUE THREAD

**Issue by rteam** [dotliquid/dotliquid#366]
Sorry, I use translation software to post    

How do I call a method with arguments? Can arguments be passed through variables? thank you

class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Template template = Template.Parse(@"
{% assign states = {{state}} %}
hi {{name}},{{states}}
{{Test.abc}}
{{Test.Data2}}
{{Test.Data }}
"); // Parses and compiles the template
            var result = template.Render(Hash.FromAnonymousObject(new { name = "tobi", state = false, Test = new TestData() })); // => "hi tobi"
            Console.WriteLine(result);
            Console.ReadKey();
        }
    }

    public class TestData : Drop
    {
        public string Nick
        {
            get { return "nick"; }
        }
        public override object BeforeMethod(string method)
        {
            return "method: " + method;
        }
        public string Data(string bcd)
        {
            return string.Concat("data", bcd);
        }

        public string Data2()
        {
            return string.Concat("data2","bcd");
        }
    }

**Comment by daviburg** [comment]
@rteam the unit tests in the dotliquid source code have many examples of passing input data.
As this is not a software issue with dotliquid but a question on how to do something that is already possibly, closing.

**Comment by icnocop** [comment]
Dotliquid doesn't support passing parameters to methods of a `Drop`.

Dotliquid only supports calling parameter-less methods of a `Drop`.

To pass parameters, use a custom `Filter` instead.
