### ISSUE TITLE
Plus filter doesn't work on typeof(uint) but does work on typeof(int)

### ISSUE THREAD

**Issue by nathansoz** [dotliquid/dotliquid#367]
### Dotliquid version
2.0.314
### Expected behavior
uint should work with the plus operator
### Actual behavior
`Liquid error: Parameter count mismatch.`
### Steps to reproduce the Problem (you can add files)
Pass a drop to a template with a single property of type uint. You should see the above error. Change to an int and it will work.

**Comment by nathansoz** [comment]
Even with an int I'm getting flaky behavior (sometimes the addition happens, sometimes it doesn't). I'll try to narrow down a repro case but for now I moved the computation to the drop.

**Comment by daviburg** [comment]
Ideally if you could provide a unit test showing the issue that would help fix this faster.

**Comment by BethSo** [comment]
I am having the same problem with times: Below, when PersonHeightFeet is 5 and PersonHeightInches is 11, "Height": comes out as 5. Not only that, but "SomeNum" is also 5. 
{%- if content.data.Booking.Subject.PersonHeightFeet -%}
						{%- if content.data.Booking.Subject.PersonHeightInches  -%}
								"Height": {{ content.data.Booking.Subject.PersonHeightFeet | times: 12 | plus: content.data.Booking.Subject.PersonHeightInches }},
								"SomeNum": {{ 5 | times: 12 }},

**Comment by daviburg** [comment]
http://dotliquidmarkup.org/try-online

{{ 5 | times: 12 }}
gives 60

Which context are you running the template in? Could it be you have Camel case filter context where you need | Times and not | times
?

**Comment by BethSo** [comment]
That was it.  Thanks.  I'm using Azure shopify liquid template transforms.

**Comment by daviburg** [comment]
Please refer for future case to this documentation:
[https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform#liquid-template-considerations](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform#liquid-template-considerations)

> If your template uses Liquid filters, make sure that you follow the DotLiquid and C# naming conventions, which use sentence casing. For all Liquid transforms, make sure that filter names in your template also use sentence casing. Otherwise, the filters won't work.
> 
> For example, when you use the replace filter, use Replace, not replace. The same rule applies if you try out examples at DotLiquid online. For more information, see Shopify Liquid filters and DotLiquid Liquid filters. The Shopify specification includes examples for each filter, so for comparison, you can try these examples at DotLiquid - Try online.

**Comment by microalps** [comment]
@daviburg issue seems to be with ExpressionUtility we are reaching "Should not get here in code". Reason is Int32 cannot be upgraded to UInt32 and vice versa because they don't overlap fully. But, they both have a common upgrade path to Int64 which is not being considered. Simple fix there is to add this line:
```
return NumericTypePromotions[right].First(p => NumericTypePromotions[left].Contains(p));
```
This returns a common upgrade path for both, in this case Int64. needs test cases built to validate this solution. In my quick testing it seems the logic is also inverted in the lines before, it is returning the downgrade instead of the upgrade type.

**Comment by microalps** [comment]
Here is a test case to prove the inversion bug:
```
Helper.AssertTemplateResult("2147483648", "{{ i | plus: i2 }}", Hash.FromAnonymousObject(new { i = (int)Int32.MaxValue, i2 = (Int64)1 }));
```
Throws an exception. So my final suggestion:
```
            // Test left to right promotion
            if (NumericTypePromotions[right].Contains(left))
                return left;
            if (NumericTypePromotions[left].Contains(right))
                return right;
            return NumericTypePromotions[right].First(p => NumericTypePromotions[left].Contains(p));
```
