### ISSUE TITLE
Filter "where" not implemented

### ISSUE THREAD

**Issue by gimmi** [dotliquid/dotliquid#374]
### Dotliquid version

2.0.333

### Expected behavior

I should be able to use the `where` filter, that is available and documented [HERE](https://shopify.github.io/liquid/filters/where/)

### Actual behavior

`where` filter not available

### Steps to reproduce the Problem (you can add files)

Just try to do a template with `where` filter in it.

I can try to provide a PR with the implementation for evaluation.

**Comment by daviburg** [comment]
Ping me if you have a PR to add this, I can help review it.

**Comment by arielbvargas** [comment]
I´ll be happy to help with that PR @gimmi. We also require the "where" filter in our project. Thanks!

**Comment by gimmi** [comment]
Here is the PR. This is based on another project of mine [DotLiquid.Extras](https://github.com/gimmi/DotLiquid.Extras) where I've implemented some useful (to me at least) extra filters.

The `where` filter should really be available in the standard one IMO

**Comment by arielbvargas** [comment]
@gimmi thanks for your PR. We´re integrating it on our solution and letting you know the results of the tests! Thanks again!!!

**Comment by miflamashood** [comment]
Is it available now?

**Comment by gimmi** [comment]
No, the PR need some cleanup in order to be merged
