### ISSUE TITLE
Removing carriage returns

### ISSUE THREAD

**Issue by pravinkarthy** [dotliquid/dotliquid#375]
### Expected behavior
Template.Parse() method should remove the "\r" carriage return character while generating the XML input template. 
### Actual behavior
Template.Parse() is not removing the "\r" carriage return character while generating the XML input template. My sample text input is something like "ABC \r\n DEF" but the rendered template has the text as "ABC \r DEF".

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.
