### ISSUE TITLE
Specify default filter.

### ISSUE THREAD

**Issue by chrisdavies** [dotliquid/dotliquid#38]
It would be nice to be able to set a global filter.  (e.g. Always HTML encode all values.)

I might expect this functionality to work like this:

Template.RegisterGlobalFilter(filter);

In this case, I'd probably make a special "unencode" filter so that if a user does NOT want HTML encoding, he/she could use this template: "Blah blah {{ name | unencode }} blah blah"

**Comment by MrJoe** [comment]
I'd like to add my 2c to this. I'd prefer to have my templates safe by default and rather add an unescape filter instead of the other way around. Having an option to add default filters would really help here.

**Comment by thuannguy** [comment]
+1. A web framework must be secure by default.
