### ISSUE TITLE
The first and last filters do not work on array with dot operator

### ISSUE THREAD

**Issue by DDAndyChen** [dotliquid/dotliquid#383]
### Dotliquid version
v2.0.314

### Expected behavior
valuates as "Jane" (view test case below)

### Actual behavior
valuates as `null`

### Steps to reproduce the Problem (you can add files)
Run the test case below

```
[Test]
        public void TestFirstOfObjectArray()
        {
            Template.RegisterSafeType(typeof(MySimpleType), new[] { "Name" });

            var array = new {
                People = new [] {
                    new MySimpleType { Name = "Jane" },
                    new MySimpleType { Name = "Mike" },
                }
            } ;

            Hash assigns = Hash.FromAnonymousObject(array);
            Helper.AssertTemplateResult("Jane", "{{ People.first.Name }}", assigns);
        }
```

**Comment by daviburg** [comment]
Something's up, I was just testing the last filter myself as well. Fails on string, works on array. Passes same template on the online test tool but fails in unit tests.

```
            Helper.AssertTemplateResult(
                expected: "Tom.",
                template: "{{ 'Ground control to Major Tom.' | split: ' ' | last }}");
            Helper.AssertTemplateResult(
                expected: "tiger",
                template: "{% assign my_array = 'zebra, octopus, giraffe, tiger' | split: ', ' %}{{ my_array.last }}");
            Helper.AssertTemplateResult(
                expected: "There goes a tiger!",
                template: "{% assign my_array = 'zebra, octopus, giraffe, tiger' | split: ', ' %}{% if my_array.last == 'tiger' %}There goes a tiger!{% endif %}");
            Helper.AssertTemplateResult(
                expected: ".",
                template: "{{ 'Ground control to Major Tom.' | last }}");
```

And for online tests:

```
This gets the last word in a string (Tom.) by splitting it
to array of strings based on space character separator:
    {{ 'Ground control to Major Tom.' | split: ' ' | last }}

This gets the last entry (tiger) of an array of strings assigned
to a variable:
    {% assign my_array = 'zebra, octopus, giraffe, tiger' | split: ', ' %}{{ my_array.last }}

This gets the last entry with dot notation and a string comparison
to display a string it matches the tiger entry:
    {% if my_array.last == "tiger" %}There goes a tiger!{% endif %}

This gets the last character (.) in a string:
    {{ 'Ground control to Major Tom.' | last }}
```

**Comment by daviburg** [comment]
The Strainer type conversion for when the type mismatches is not recognizing when a type implements a requested interface input type and the .NET Convert is failing the conversion.

**Comment by daviburg** [comment]
Fixing the Strainer problem fixes the problem wit the string convert attempt to enumerable but does not fix the problem with array reported here.

**Comment by daviburg** [comment]
For the problem reported here and its reproduction example the variable search in the context is not returning a match (returns null).

**Comment by daviburg** [comment]
Context.Variable is correctly recognizing the array as an enumerable, the part as the reserved first filter and picks the first element of the array.

**Comment by daviburg** [comment]
The problem is not with the first and last filters, the problem is that the simple type registered as safe isn't wrapped in a DropProxy when inputted that way in an array. The array first-last filter look-up work, it's the name part lookup that fails because the simple type isn't wrapped.

**Comment by daviburg** [comment]
And this is because Context::Variable parts look-up escape for first and last filters lacks the call to Liquidize which other ~collections look-up have. Fix coming up.
