### ISSUE TITLE
%b date format doesn't parse - renders just the b letter

### ISSUE THREAD

**Issue by daviburg** [dotliquid/dotliquid#391]
### Dotliquid version
Current as of 6-13-2020

### Expected behavior
As per she shopify sample for date filter https://shopify.github.io/liquid/filters/date/
`{{ "March 14, 2016" | date: "%b %d, %y" }}`
must render
`Mar 14, 16`

### Actual behavior
Renders instead
`b 14, 16`

### Steps to reproduce the Problem (you can add files)
```
            Helper.AssertTemplateResult(
                expected: "Mar 14, 16",
                template: "{{ \"March 14, 2016\" | date: \"%b %d, %y\" }}");
```

Note: i see there is code intended for this format but not working

`            { "b", (dateTime) => dateTime.ToString("MMM", CultureInfo.CurrentCulture) },`

at https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/Util/StrFTime.cs#L15

**Comment by daviburg** [comment]
More problems with following the Shopify spec samples;
```
            Helper.AssertTemplateResult(
                expected: $"This page was last updated at {DateTime.Now.ToString("yyyy-MM-dd HH:mm")}.",
                template: "This page was last updated at {{ 'now' | date: '%Y-%m-%d %H:%M' }}.");
```

**Comment by sstraus** [comment]
Try Liquid.UseRubyDateFormat = true

**Comment by microalps** [comment]
Uncommented and moved to correct test  in #420. Please close @daviburg

**Comment by daviburg** [comment]
Instead we need to link open PR to issues like this, and completing the PR will close the issues.
