### ISSUE TITLE
Question: Run Time Errors

### ISSUE THREAD

**Issue by nathanaskinner** [dotliquid/dotliquid#392]
A question, not an issue. 

How is finding run time errors through debug handled with dotLiquid?

**Comment by daviburg** [comment]
There is a specific string for liquid error added to the output, if that's what you are seeing, and you can put a breakpoint on the line of code that catch exception and handles it to error input.

**Comment by microalps** [comment]
@nathanaskinner if this resolved your question, please close the issue. This will be closed in a week if no response

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.
