### ISSUE TITLE
Sort filter does not follow casing behavior from Shopify's specification

### ISSUE THREAD

**Issue by daviburg** [dotliquid/dotliquid#393]
### Dotliquid version
Current as of 6-22-2020

### Expected behavior
Shopify specification compliant behavior case sensitive sorting
```

Sally Snake, giraffe, octopus, zebra
```
https://shopify.github.io/liquid/filters/sort/

### Actual behavior
Sort natural filter case insensitive behavior is implemented instead

```

giraffe, octopus, Sally Snake, zebra
```

https://shopify.github.io/liquid/filters/sort_natural/

### Steps to reproduce the Problem (you can add files)
Use online try liquid with the Shopify sample

```
{% assign my_array = "zebra, octopus, giraffe, Sally Snake" | split: ", " %}

{{ my_array | sort | join: ", " }}
```

**Comment by microalps** [comment]
We will need to add Sort_Natural before commiting this. Issue #330
