### ISSUE TITLE
Implement Truthiness of types Unit Tests

### ISSUE THREAD

**Issue by daviburg** [dotliquid/dotliquid#394]
### Dotliquid version
Current as of 6-23-2020

### Expected behavior
> All values in Liquid are truthy except nil and false.

Text should appear because 

> the text "Tobi" is not a boolean, but it is truthy in a conditional

### Actual behavior
Blank output, text does not appear

### Steps to reproduce the Problem (you can add files)
got to http://dotliquidmarkup.org/try-online
paste
```
{% assign name = "Tobi" %}

{% if name == true %}
  This text will always appear if "name" is defined.
{% endif %}
```

**Comment by daviburg** [comment]
Internally the match condition is trying to convert the types of the two operands to find a common ground, settles on string (as boolean can be converted to string value 'True' or 'False'). But instead we should overwrite the behavior and special case when either of the operand is boolean and not the other, the other type needs to follow the Shopify 'Truthiness' spec.

**Comment by daviburg** [comment]
For backward compatibility reasons we should probably put this and other spec compliance fixes behind a flag for strict Shopify specification compliance.

**Comment by jolleekin** [comment]
That is expected. You're trying to compare `"Tobi"` and `true`, which are completely different (by type and by value). What you should write instead is
```
{% assign name = "Tobi" %}

{% if name %}
  This text will always appear if "name" is defined.
{% endif %}
```

**Comment by daviburg** [comment]
That 'name' would be truthy is consistent with example in
https://shopify.github.io/liquid/basics/truthy-and-falsy/

> ### Truthy
> All values in Liquid are truthy except **nil** and **false**.
> 
> In the example below, the string “Tobi” is not a boolean, but it is truthy in a conditional:
```
{% assign tobi = "Tobi" %}

{% if tobi %}
  This condition will always be true.
{% endif %}
```
> Strings, even when empty, are truthy. The example below will result in empty HTML tags if **settings.fp_heading** is empty:
> 
> Input

```
{% if settings.fp_heading %}
  <h1>{{ settings.fp_heading }}</h1>
{% endif %}
```
> Output

`<h1></h1>`

But consider also same specification with additional details at https://shopify.dev/docs/themes/liquid/reference/basics/true-and-false
Which gives the explicit cross-type equality example:

> In the example below, the text "Tobi" is not a boolean, but it is truthy in a conditional:
```
{% assign name = "Tobi" %}

{% if name == true %}
  This text will always appear if "name" is defined.
{% endif %}
```
@jolleekin comparing string and true are equal as per public and explicit specification by Shopify.

**Comment by jolleekin** [comment]
For reference, in JS, `"Tobi"` and `true` are both truthy, but **are not** equal. It's common sense that they are not equal.

Shopify's spec doesn't say anything about comparing values of different types.

**Comment by daviburg** [comment]
@jolleekin the above quotes and samples **ARE** from Shopify. If you disagree with Shopify you will need to take it directly with them. I understand your argument that the types are different as a general programming concept, but that is just not the way Shopify specified the truthy and equality concepts for Liquid. And dotLiquid has to follow the spec.

**Comment by jolleekin** [comment]
@daviburg It's likely that the docs author made a mistake when writing `{% if name == true %}`. I'm confident that this evaluates to `false` using Ruby Liquid just by looking at the source code.

https://github.com/Shopify/liquid/blob/master/lib/liquid/condition.rb#L13
https://github.com/Shopify/liquid/blob/master/lib/liquid/condition.rb#L128
https://github.com/Shopify/liquid/blob/master/lib/liquid/condition.rb#L143

You may confirm this by installing the Liquid gem and trying it out.

**Comment by sebastienros** [comment]
I created a PR on the liquid repository to check the documentation, and it looks like the doc is wrong since the tests I added pass.

https://github.com/Shopify/liquid/pull/1372

**Comment by daviburg** [comment]
Does Shopify has a process to report documentation bugs?

**Comment by sebastienros** [comment]
I am waiting on people to react to the PR to give guidance or see how they react in the docs.

**Comment by daviburg** [comment]
They removed the comparison of string to boolean from the docs.

**Comment by daviburg** [comment]
Now that Shopify cleaned-up the spec, we probably should anchor the behavior by adding "tobi" truthy, falsy, and non-explicit boolean cross type comparison unit tests to DotLiquid.

**Comment by robin-parker** [comment]
@daviburg - I this is covered by the TestIsTruthy_ShopifySample1/TestIsTruthy_ShopifySample1 tests added to ObjectExtensionMethodsTests.cs in PR #434

**Comment by daviburg** [comment]
Apologies. This got lost in my inbox. Yes, completely fine to close.
