### ISSUE TITLE
Wrong size property checks

### ISSUE THREAD

**Issue by sebastienros** [dotliquid/dotliquid#395]
```
{% assign foo = '' %}
{% if foo.size != 0 %}true{% else %}false{% endif %}
{% if foo.size == 0 %}true{% else %}false{% endif %}
{% if foo.size > 0 %}true{% else %}false{% endif %}
{% if foo.size < 0 %}true{% else %}false{% endif %}
```

```
false
true
true
true
```

**Comment by microalps** [comment]
@sebastienros  are you able to reproduce this on current release? I went back a few versions and got true just for the second one.

**Comment by sebastienros** [comment]
I might have used the website, which I assume could use a very old version. So I will trust your test. Can you update the issue?

**Comment by sebastienros** [comment]
If update doesn't mean "close"

**Comment by microalps** [comment]
I dont have right access. You should have close issue link as author.
