### ISSUE TITLE
Adding days doesn't work with Shopify's DotLiquid pattern

### ISSUE THREAD

**Issue by sstraus** [dotliquid/dotliquid#400]
### Dotliquid version
Latest
### Expected behavior
Add 14 days to now
### Actual behavior
String concatenation instead of addition resulting in test: 16012856991209600
### Steps to reproduce the Problem (you can add files)

Liquid.UseRubyDateFormat = true;
Template template = Template.Parse(@"test: {% assign seconds = 14 | times: 24 | times: 60 | times: 60 %}{{mydate | date: ""%s"" | plus: seconds | date: ""%a, %b %d, %y"" }}"); 
Console.WriteLine(template.Render(Hash.FromAnonymousObject(new { mydate = DateTime.Now })));

This is a common pattern in Shopify's DotLiquid to add days to dates.

You can test it here: https://dotnetfiddle.net/LoBHn0

**Comment by sstraus** [comment]
BTW plus should not concat string but just sum as explained in the docs https://shopify.github.io/liquid/filters/plus/

**Comment by nicwillemse** [comment]
Is there a work around for this ?

**Comment by microalps** [comment]
@sstraus please confirm #420 completely resolves this issue and if so close #401
