### ISSUE TITLE
Number Conversion Inconsistent with Ruby Implementation

### ISSUE THREAD

**Issue by mhornbacher** [dotliquid/dotliquid#404]
### Dotliquid version
2.0.366

### Expected behavior
`{{  '5' | plus: 5 }}` should output `10`
`{{  '5' | times: 5 }}` should output `25`
`{{  '5' | minus: 5 }}` should output `0`
`{{  '21' | divided_by: 3 }}` should output `7`
`{{ '8888' | modulo: 10 }}` should output `8`

### Actual behavior
`{{  '5' | plus: 5 }}` outputs `55`
`{{  '5' | times: 5 }}` outputs `55555`
`{{  '5' | minus: 5 }}` outputs `Liquid error: Parameter count mismatch.`
`{{  '21' | divided_by: 3 }}` outputs `Liquid error: Parameter count mismatch.`
`{{ '8888' | modulo:10 }}` outputs `Liquid error: Parameter count mismatch.`

### Steps to reproduce the Problem (you can add files)
Add test cases above to `StandardFilterTests`

### Description/Notes
In the ruby implementation from Shopify all mathematical operators use this method which attempts to convert the inputs to numbers regardless of their data type:

https://github.com/Shopify/liquid/blob/1850511334c555b74232166006a19e987ae7a41d/lib/liquid/standardfilters.rb#L453

However this implementation (`StandardFilters.cs`) uses `IsReal` which checks the .NET runtime type of the properties passed in.

There are also some cases such as `plus` and `times` which have explicitly different behavior in the case of `string` types compared with the `ruby` implementation. As such changing this to be consistent with ruby would be a breaking change.

Also in this implementation, if you change the operand to a floating point (`float`, `decimal` or `double`) we do attempt to convert the `input` in the cases of `minus`, `divided_by` and `modulo`. Which is in itself inconsistent behavior.

**Comment by mhornbacher** [comment]
I can write a simple fix for this. What is the policy around proposing breaking changes like this?

**Comment by sebastienros** [comment]
Are you sure `{{ '5' | plus: 5.0 }}` should output `10`, I would have said that it should output `10.0` since it has to respect the precision.

**Comment by sebastienros** [comment]
For reference:

https://github.com/Shopify/liquid/blob/dbaef5e79bd865a8082c63053e73bb6ce2c7b44f/test/integration/standard_filter_test.rb#L546

**Comment by mhornbacher** [comment]
Your right, it should output `10.0`, but the main bug is when the addition is not a floating point.

**Comment by microalps** [comment]
Duplicate of #400

**Comment by daviburg** [comment]
I think they are related but not identical. This here covers the number types while #400 covers the date types.

**Comment by daviburg** [comment]
How do you run "the ruby implementation" from Visual Studio? I've only used DotLiquid with .NET so I'm very unfamiliar with Ruby.

**Comment by daviburg** [comment]
And do we have any Ruby dev around who could start fixing these glary issues?

**Comment by mhornbacher** [comment]
The Ruby implementation is the base implementation of the templating language that this is based on. Essentially its about if the behavior is the same or not.

I can make a PR to fix this today, however it will be a backwards-incompatible breaking change and should likely be included in a larger release.

**Comment by microalps** [comment]
@mhornbacher I spoke with @daviburg and he wants to see all the incompatible with ruby liquid in a PR with a toggle to enable the Strict Liquid Syntax

**Comment by mhornbacher** [comment]
Hu, that might take me a bit longer. I'll have to setup the ruby implementation on my system and consider how to pass that flag around. Not sure I'll have time for that today but I'll segment some time on my calendar to take a crack at it.

I assume this includes what was reported in #400 as well?

**Comment by daviburg** [comment]
Thanks. In general breaking changes are best kept under opt-in flag so DotLiquid consumers can continue picking non-breaking updates. As we have a number of specification compliance issues, it seems to make sense to gather them under one common flag. Yes #400 is one of these compliance issues.

**Comment by microalps** [comment]
@mhornbacher Does PR #420 fully resolve your issue?

**Comment by mhornbacher** [comment]
Looks like it should!

**Comment by microalps** [comment]
@mhornbacher would you like to contribute some more fixes related to date? We are discussing missing epoch handling and epoch output not working outside of UTC timezome on gitter.im and I'd love to get input or code assistance.

**Comment by mhornbacher** [comment]
I can take a look. We had a massive religious holiday and there where 3 weddings all over the last weekend. But if I can find the time sure :)

**Comment by microalps** [comment]
We got epoch handling done. Anyways, jump on gitter :)
