### ISSUE TITLE
AppVeyor: NuGet API key expired

### ISSUE THREAD

**Issue by fubar-coder** [dotliquid/dotliquid#410]
### Dotliquid version

n/a

### Expected behavior

IT seems that all commits to the master branch are automatically compiled and uploaded to NuGet. It's expected that the NuGet upload succeeds.

### Actual behavior

NuGet upload fails due to an expired API key.

### Steps to reproduce the Problem (you can add files)

Just take a look at the AppVeyor build logs

**Comment by microalps** [comment]
Can @daviburg or @tgjones Close this? Resolved.

**Comment by microalps** [comment]
This is happening again, @daviburg or @tgjones have access to fix?

**Comment by daviburg** [comment]
I don't fully remember but I think only @tgjones had access to the AppVeyor account last time.
