### ISSUE TITLE
Whitespace control is incompatible with Shopify's docs

### ISSUE THREAD

**Issue by jolleekin** [dotliquid/dotliquid#411]
### Sample code
```liquid
# Without whitespace control
{% assign name = 'John G. Chalmers-Smith' %}
{% if name and name.size > 10 %}
    Wow, {{ name }}, you have a long name!
{% else %}
    Hello there!
{% endif %}

# With whitespace control
{% assign name = 'John G. Chalmers-Smith' -%}
{%- if name and name.size > 10 -%}
    Wow, {{ name }}, you have a long name!
{%- else -%}
    Hello there!
{%- endif -%}
```
### Dotliquid version
Unknown (using DotLiquid Online)

### Expected behavior
```
# Without whitespace control


    Wow, John G. Chalmers-Smith, you have a long name!


# With whitespace control
Wow, John G. Chalmers-Smith, you have a long name!
```
Generated by [LiquidJS](https://liquidjs.com/playground.html#IyBXaXRob3V0IHdoaXRlc3BhY2UgY29udHJvbA0KeyUgYXNzaWduIG5hbWUgPSAnSm9obiBHLiBDaGFsbWVycy1TbWl0aCcgJX0NCnslIGlmIG5hbWUgYW5kIG5hbWUuc2l6ZSA+IDEwICV9DQogICAgV293LCB7eyBuYW1lIH19LCB5b3UgaGF2ZSBhIGxvbmcgbmFtZSENCnslIGVsc2UgJX0NCiAgICBIZWxsbyB0aGVyZSENCnslIGVuZGlmICV9DQoNCiMgV2l0aCB3aGl0ZXNwYWNlIGNvbnRyb2wNCnslIGFzc2lnbiBuYW1lID0gJ0pvaG4gRy4gQ2hhbG1lcnMtU21pdGgnIC0lfQ0KeyUtIGlmIG5hbWUgYW5kIG5hbWUuc2l6ZSA+IDEwIC0lfQ0KICAgIFdvdywge3sgbmFtZSB9fSwgeW91IGhhdmUgYSBsb25nIG5hbWUhDQp7JS0gZWxzZSAtJX0NCiAgICBIZWxsbyB0aGVyZSENCnslLSBlbmRpZiAtJX0=)

### Actual behavior
```
# Without whitespace control


    Wow, John G. Chalmers-Smith, you have a long name!


# With whitespace control
    Wow, John G. Chalmers-Smith, you have a long name!
```
Generated by http://dotliquidmarkup.org/try-online
### References
- https://shopify.github.io/liquid/basics/whitespace/

**Comment by microalps** [comment]
Interesting to note that the documentation does describe it differently than Liquid. See https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers#line-breaks for a description and example that diverge from the reference library.

For sake of clarity, it seems that the hyphen at the beginning of a tag removes tabs and spaces but not new lines. Hyphens at the end remove new lines or tabs+spaces but not both. The reference library uses ruby native trim which removes ascii 9-13 (tab, line feed, form feed,  and space.

**Comment by HenrikPoulsen** [comment]
I ran into this today as well when I noticed that liquidjs [playground](https://liquidjs.com/playground.html#eyUgYXNzaWduIHRoaW5ncyA9ICJhbGljZSwgYm9iLCBjYXJvbCIgfCBzcGxpdDogIiwgIiAtJX0KCmRlcGVuZGVuY2llczoKICAgIC0gYSBoYXJkY29kZWQgdGhpbmcKeyUgZm9yIHRoaW5nIGluIHRoaW5ncyAtJX0KICAgIC0ge3sgdGhpbmcgfX0KeyUgZW5kZm9yIC0lfQo=) and dotliquid disagree when it comes to whitespaces. And you can end up with lists with broken indentation when one tries to import liquid yaml which was validated with dotliquid when then trying to render and parse that using liquidjs.
Which is exactly the situation I found myself in
