### ISSUE TITLE
Parse error when string literals contain }} or %}

### ISSUE THREAD

**Issue by jolleekin** [dotliquid/dotliquid#412]
### Dotliquid version
Unknown (using Dotliquid online)

### Input
```liquid
{{ '{{ {% %} }}' }}
{% assign x = '{{ {% %} }}' %}
{{ x }} 
```

### Expected output
```
{{ {% %} }}

{{ {% %} }}
```

### Actual output
An exception is thrown

**Comment by microalps** [comment]
This is not supported in Ruby. I noticed the author reported to jsliquid as well. @jolleekin Do you use DotLiquid?

**Comment by microalps** [comment]
Yes, he reported the issue in https://github.com/harttle/liquidjs/issues/288 and they fixed just to close the issue even though
>It's by design. To output raw string literals, use raw. 
Again, if it's not a real issue of a user of DotLiquid, this gets the back burner.

**Comment by jolleekin** [comment]
@microalps This should not be by design but a flaw due to a non-robust implementation (relying too much on regular expression).

I was evaluating Liquid to see if it's suitable for my company's need. To be specific, we need a Dart package for the client and a C# package for the server. I found [liquid_engine](https://pub.dev/packages/liquid_engine), DotLiquid, [Fluid](https://github.com/sebastienros/fluid), and [Scriban](https://github.com/scriban/scriban). However, I realized there are so many differences among Liquid implementations due to lack of an official language spec. In addition, Liquid itself is pretty limited (no array literal, no object literal, too simple expressions, ...). Therefore, we decided to create our own language. It's still work in progress.

**Comment by sebastienros** [comment]
@jolleekin are you open sourcing it? Please share a link if so, I would love to see how you intend to add these features. I would have personally used Scriban in that case, but since there is no implementation in Dart it might just be the opportunity to create your own syntax. Or implement Scriban in Dart ...
