### ISSUE TITLE
[Security] Unrecognized filters don't trigger a rendering error/exception

### ISSUE THREAD

**Issue by benjamincburns** [dotliquid/dotliquid#413]
### Dotliquid version
2.0.366

### Expected behavior

Assuming that no custom filters are registered, attempting to render a template like `{{ "hello world" | unknownfilter }}` should throw an exception.

This is an important problem because template filters are often used as a guard against information leakage (e.g. masking secrets) and injection vulnerabilities (string escaping, etc). Ideally developers would write tests to ensure that these facilities are working properly (I found this issue by writing such tests), but in the real world that often doesn't happen. Many devs will incorrectly assume that unrecognized filters will trigger an exception, and therefore assume that if the template renders without throwing, their filters are safeguarding their system correctly, and explicit tests to verify this will be treated as a low priority due to these assumptions.

### Actual behavior

The missing filter is ignored and the template renders as if it were written `{{ "hello world" }}`.

**Comment by benjamincburns** [comment]
I'm assuming that it works this way because this is how the official liquid renderer appears to behave. That doesn't mean that it's a good idea, however.

https://github.com/Shopify/liquid/issues/422

**Comment by benjamincburns** [comment]
It looks like the problem is in `Context.Invoke` [here](https://github.com/dotliquid/dotliquid/blob/0c4ad937cfc8041f3c10b13c946f1be56383432d/src/DotLiquid/Context.cs#L227). Instead of returning the original value that was passed to the filter, it should throw.

I'd be happy to submit a PR for this if it will be accepted.

**Comment by microalps** [comment]
@benjamincburns I would review such a PR if it was locked behind DotLiquid Syntax Compatibility and part of a series of compatibility changes. See related issues with behavior change tags as those are in my radar for the next batch.

**Comment by microalps** [comment]
(In case it is unclear what I mean by 'locked behind DotLiquid Syntax Compatibility' - See https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid/SyntaxCompatibilityEnum.cs and next series in #431

**Comment by benjamincburns** [comment]
Just to make sure that I understand, any logic introduced by this change would need to be conditional on the compatibility flag being `>= DotLiquid21`, correct?

**Comment by microalps** [comment]
DotLiquid21 is already released. DotLiquid21a is the next version.
