### ISSUE TITLE
how do I  loop  the Dictionary<string, object>

### ISSUE THREAD

**Issue by destinyclown** [dotliquid/dotliquid#414]
### Dotliquid version
2.0.366
### Expected behavior
![image](https://user-images.githubusercontent.com/10192335/105689051-41fdf580-5f35-11eb-9833-4699056560b0.png)
please help me ,how can I loop the Data
### Steps to reproduce the Problem (you can add files)

**Comment by microalps** [comment]
Seems like a duplicate of #320
