### ISSUE TITLE
Cannot bind property of an ExpandoObject that is inside an array

### ISSUE THREAD

**Issue by laksh-parab** [dotliquid/dotliquid#417]
Looks like we are unable bind a property of an ExpandoObject when that object is inside an array and when we use `Hash.FromDictionary`

[NETfiddle Demo](https://dotnetfiddle.net/Ky9s0x)

`
   
            public class Program
            {
                public static void Main()
                {
                    // this does not work		
                    var modelString = "{\"States\": [{\"Name\": \"Texas\",\"Code\": \"TX\"}, {\"Name\": \"New York\",\"Code\": \"NY\"}]}";
                    var template = "State Is:{{States[0].Name}}";
                    RenderFromDictionary(modelString, template);

                    //this works
                    modelString = "{\"States\": [\"Texas\",\"New York\"]}";
                    template = "State Is:{{States[0]}}";
                    RenderFromDictionary(modelString, template);

                    //this works
                    var anonymoudmodel = new { States = new[] { new { Name = "Texas", Code = "TX" }, new { Name = "New York", Code = "NY" } } };
                    template = "State Is:{{States[0].Name}}";
                    RenderFromAnonymousObject(anonymoudmodel, template);
                }

                private static void RenderFromDictionary(string modelString, string template)
                {
                    var model = JsonConvert.DeserializeObject<ExpandoObject>(modelString);
                    var templateModel = Hash.FromDictionary(model);
                    var html = Template.Parse(template).Render(templateModel);
                    Console.WriteLine(html);
                }

                private static void RenderFromAnonymousObject(dynamic model, string template)
                {
                    var templateModel = Hash.FromAnonymousObject(model);
                    var html = Template.Parse(template).Render(templateModel);
                    Console.WriteLine(html);
                }
            }

`

**Comment by laksh-parab** [comment]
Looks like this is a bug in the following code in **Hash.cs** If the value is type of IEnumerable then Its not converting individual item of the collection  to Hash object

        public static Hash FromDictionary(IDictionary<string, object> dictionary)
        {
            Hash result = new Hash();

            foreach (var keyValue in dictionary)
            {
                    if (keyValue.Value is IDictionary<string, object>)
                    {
                        result.Add(keyValue.Key, FromDictionary((IDictionary<string, object>) keyValue.Value));
                    }
                    else
                    {
                        result.Add(keyValue);
                    }
            }
                
            return result;
        }

**Comment by laksh-parab** [comment]
Since `Hash` & `ExapndoObject` both are is derived IDictionary<string,object> to add support for `ExpandoObject` I see 2 options 
1>Update Hash.FromDictionary() method so that it will convert individual collection item of type ExpandoObject to `IDictionary<string,object>`

or

2> update `IsHashOrArrayLikeObject()`  and `LookupAndEvaluate()` methods with the following code with additional check for `IDictionary<string, object>`

        private static bool IsHashOrArrayLikeObject(object obj, object part)
        {
            if (obj == null)
                return false;

            if ((obj is IDictionary && ((IDictionary)obj).Contains(part)))
                return true;

            **if ((obj is IDictionary<string, object> && ((IDictionary<string, object>)obj).ContainsKey(part.ToString())))
                return true;**

               // rest of the code
        }

        private object LookupAndEvaluate(object obj, object key)
        {
            object value;
            if (obj is IDictionary dictionaryObj)
            {
                value = dictionaryObj[key];
            }
            **else if (obj is IDictionary<string, object> dictionaryObject)
            {
                value = dictionaryObject[key.ToString()];
            }**

             // rest of the code
        }

**Comment by microalps** [comment]
@laksh-parab good catch, Expando was implemented is PR #262 but not handling this scenario of ienumerable. Do you mind creating a PR, I would go with approach 1 personally since that is how the previous PR went with and you must call FromDictionary.

**Comment by microalps** [comment]
This relates to #414 we can kill two birds.
