### ISSUE TITLE
Strict Liquid Syntax

### ISSUE THREAD

**Issue by microalps** [dotliquid/dotliquid#419]
This is a placeholder for various changes, for good or for worse, that are needed to make DotLiquid behave similar to the reference Liquid language. This will include breaking changes if enabled, but remain disabled by default (possibly until a major version release).

**Comment by microalps** [comment]
## Issue 1: Ruby Date Formatting
As reported in #391 - DotLiquid does not support flags that are part of the ruby language https://www.rubydoc.info/stdlib/date/Date:strftime

## Issue 2: Date Math
As reported in #400 and #404 - DotLiquid falls back to append behavior when presented with a string and plus filter. Reference library instead casts to a numeric and does math as expected. String can be a result of inline hard-coded string `{{ '5' | plus: 5 }}` or result of date filter `{{mydate | date: "%s" | plus: 84600 }}`

## Issue 3: Replace / ReplaceFirst Behavior
As reported in #385 - DotLiquid uses Regex to replace instead of simple string replacement. This is an unexpected behavior although more powerful. 

## Issue 4: Capitalize is Title Case
As reported in #390 - DotLiquid capitalizes each work in a given string. The documentation clearly states only the first character should be capitalized and all later words are not affected. https://shopify.github.io/liquid/filters/capitalize/

**Comment by microalps** [comment]
Issue 2, 3, and 4 are fully implemented with backward compatibility. @daviburg (1) Are the remaining issues problematic to fix for all versions? Seems non-breaking to me (2) Do we need a commit for truthiness that you brought up as being different?

**Comment by daviburg** [comment]
Added comment in https://github.com/dotliquid/dotliquid/issues/342

**Comment by daviburg** [comment]
Yes both issues referred under 6 can be fixed in place without a version flag.

**Comment by daviburg** [comment]
Shopify published the fix to the examples of truthiness in their spec. So we might be in compliance with the revised spec. What was that issue number again? https://github.com/dotliquid/dotliquid/issues/394 
Oh, as per my last comment there we simply should be added unit tests now. No functional change there.

**Comment by daviburg** [comment]
For #419 when following strict liquid syntax, should the "Ruby" format be followed by default, to be actually as per the Shopify spec?

**Comment by microalps** [comment]
Since the ruby spec is incomplete I would say not in this version for sure. Also, since the strict syntax is not necessarily global but the ruby date is, we cannot marry those two until they are compatible in scope.  Finally, I prefer the .net syntax personally and I'm sure most of the devs are likewise using it. Otherwise we'd have dozens of bugs reported with it's incomplete implementation.

**Comment by daviburg** [comment]
Sounds like completing the implementation of the Ruby date format in DotLiquid is the first step. Maybe the second is to be able to control the date format via local parameter superseding legacy global parameter. Then we can reconsider whether this is a point of strict Liquid Syntax compliance.
I understand that specific consumer will have different preference in the format. An important aspect to consider is the ability to re-use assets between the implementations (Shopify, DotLiquid, Fluid, etc...) and that's where a strict compliance option pays-in. Date format is part of what the assets may use (and if differently implemented, break).

**Comment by microalps** [comment]
Let's discuss the above in #251 and gitter please. I'm moving my comments to there. Let's move ahead with the rest please. I won't have the capacity to spend much effort on that personally to be honest for a while.
