### ISSUE TITLE
REGRESSION: Incorrect Ruby output for DateTimeOffset

### ISSUE THREAD

**Issue by mhornbacher** [dotliquid/dotliquid#423]
### Dotliquid version
v1.6.1

### Expected behavior
`.ToStrFTime` should work for `DateTimeOffset` just as it works for `DateTime`

### Actual behavior

Applying the test suite to a `DateTimeOffset` offset object shows that the following formats fail:

Errors:
- `%` -> `System.ArgumentOutOfRangeException : Index and length must refer to a location within the string.`

| format | expected | was |
| ------- | ---------- | ---- |
| %c | Sun Jan 08 14:32:14 2012 | Sun Jan 08 00:00:00 2012 |
| %H | 14 | 00 |
| %I | 02 | 12 |
| %k | 14 | 0 |
| %l | 2 | 12 |
| %M | 32 | 00 |
| %p | PM | AM |
| %P | pm | am |
| %S | 14 | 00 |
| %X | 14:32:14 | 00:00:00 |

### Steps to reproduce the Problem (you can add files)

Add the following to `StfFTimeTests`

```csharp
[TestCase("%a", ExpectedResult = "Sun")]
[TestCase("%A", ExpectedResult = "Sunday")]
[TestCase("%b", ExpectedResult = "Jan")]
[TestCase("%B", ExpectedResult = "January")]
[TestCase("%c", ExpectedResult = "Sun Jan 08 14:32:14 2012")]
[TestCase("%C", ExpectedResult = "20")]
[TestCase("%d", ExpectedResult = "08")]
[TestCase("%e", ExpectedResult = " 8")]
[TestCase("%h", ExpectedResult = "Jan")]
[TestCase("%H", ExpectedResult = "14")]
[TestCase("%I", ExpectedResult = "02")]
[TestCase("%j", ExpectedResult = "008")]
[TestCase("%k", ExpectedResult = "14")]
[TestCase("%l", ExpectedResult = "2")]
[TestCase("%m", ExpectedResult = "01")]
[TestCase("%M", ExpectedResult = "32")]
[TestCase("%P", ExpectedResult = "pm")]
[TestCase("%p", ExpectedResult = "PM")]
[TestCase("%s", ExpectedResult = "1326033134")]
[TestCase("%S", ExpectedResult = "14")]
[TestCase("%u", ExpectedResult = "7")]
[TestCase("%U", ExpectedResult = "02")]
[TestCase("%W", ExpectedResult = "01")]
[TestCase("%w", ExpectedResult = "0")]
[TestCase("%x", ExpectedResult = "08/01/2012")]
[TestCase("%X", ExpectedResult = "14:32:14")]
[TestCase("%y", ExpectedResult = "12")]
[TestCase("%Y", ExpectedResult = "2012")]
[TestCase("%", ExpectedResult = "%")]
public string TestOffsetFormat(string format)
{
    using (CultureHelper.SetCulture("en-GB"))
    {
        Assert.That(CultureInfo.CurrentCulture, Is.EqualTo(new CultureInfo("en-GB")));
        return new DateTimeOffset(2012, 1, 8, 14, 32, 14, TimeSpan.FromHours(0)).ToStrFTime(format);
    }
}
```

### Causes

The cause of the exception is due to an off by one error when checking that there is a follow up character to the `%` marker. This can be fixed by adjusting the if statment like so:

`if (s == "%" && pattern.Length > n + 1)`

The cause of the changes is the table is due to `dateTime.Date` being passed into the `DateTime` formatters rather than `dateTime.DateTime` which is stripping the time information from the date. Updating this fixes the entire table.

**Comment by microalps** [comment]
Please review my comments and I will approve.

**Comment by mhornbacher** [comment]
@microalps reviewed your comments :)

**Comment by microalps** [comment]
I didn't follow - are you going to update the tests  or not? I've locally run my own tests, so the fix is good...

**Comment by mhornbacher** [comment]
Yea, sorry got pulled aside (other work issues ;)) pushing now
