### ISSUE TITLE
comment tag was never closed

### ISSUE THREAD

**Issue by yufeih** [dotliquid/dotliquid#439]
### Dotliquid version
2.1.457

### Expected behavior
Liquid template parse successfully

### Actual behavior
Liquid template parse failed with `SyntaxException`: 

```
DotLiquid.Exceptions.SyntaxException : comment tag was never closed
  Stack Trace:
     at DotLiquid.Tokenizer.Tokenize(String source)
   at DotLiquid.Template.Tokenize(String source)
   at DotLiquid.Template.ParseInternal(String source)
   at DotLiquid.Template.Parse(String source)
```

### Steps to reproduce the Problem (you can add files)

Parse this liquid file. It succeeds in 2.1.405.
```liquid
{%- comment -%} a {%- endcomment -%}
```

https://github.com/dotnet/docfx/pull/7442

**Comment by daviburg** [comment]
Which part of the Shopify spec allows dash '-' characters in the blocks? I see comment and raw blocks explained without this:
https://shopify.github.io/liquid/tags/template/

**Comment by yufeih** [comment]
> In Liquid, you can include a hyphen in your tag syntax {{-, -}}, {%-, and -%} to strip whitespace from the left or right side of a rendered tag.

https://shopify.github.io/liquid/basics/whitespace/

**Comment by daviburg** [comment]
Thx
