### ISSUE TITLE
Doesn't appear to be a way to get the current date/time

### ISSUE THREAD

**Issue by Jaben** [dotliquid/dotliquid#45]
According to docs, this should be the current date/time:

  {{ 'now' | date: "MM/dd/yyyy" }}

Looking at the code, there is no way to get the current date time. 

Minor to fix:

	public static string Date(object input, string format)
        {
        	if (input == null) return null;

        	if (format.IsNullOrWhiteSpace()) return input.ToString();

        	DateTime date = DateTime.Now;

        	if (string.Compare(input.ToString(), "now", StringComparison.InvariantCultureIgnoreCase) == 0 || DateTime.TryParse(input.ToString(), out date))
        	{
        		return Liquid.UseRubyDateFormat ? date.ToStrFTime(format) : date.ToString(format);
        	}
        	  
		return input.ToString();
        }

**Comment by dcs619** [comment]
I realize this issue is 4 years old, but the official repo now supports using 'now' or 'today' in Liquid markup: https://github.com/Shopify/liquid/commit/8ca4868bff27d1aa225938c0e36148c3a5bb61b0#diff-844406140a08cdeddd843cfbdf0222d6R183

Any chance this issue could be reopened?  Apologies in advance if I've missed another way to get the current date/time.

**Comment by rdumont** [comment]
Since Liquid has had this implemented for almost two years now, we really should consider also adding support to `now` and `today`.

**Comment by dcs619** [comment]
@rdumont Did you see my comment?  Now and Today are supported.

**Comment by rdumont** [comment]
@dcs619 I don't think they are, not by DotLiquid. I just tested this with DotLiquid's master branch.

**Comment by canerelci** [comment]
As @rdumont says, it's not supported by master branch, I have a quick implementation of 'now' and 'nowutc' in my branch. In fact, 'now' was my reason to create a branch months ago. 

'today' would also be nice but I think it will be just an alias for 'now'?

**Comment by haf** [comment]
Would indeed be nice; PR PR PR ;).

**Comment by sbcp1993** [comment]
> {{ 'Now' | Date:'MM/dd/yy' }}

No luck with this. I still get the 'Now' string using this.
