### ISSUE TITLE
use of 'now' with Date not working

### ISSUE THREAD

**Issue by sbcp1993** [dotliquid/dotliquid#454]
Hi, 

I want to get the current UTC time for my template. I tried the following,
```
{
    "DateCreated": {{ "Now" | Date: "yyyy-MM-ddTHH:mm:ss" }}
}
```

But this results in 

```
{
    "DateCreated": "Now"
}

```
I also tried it with 'now' (small n) but not getting the result I want.

Can anyone help me with this ?

Thanks

**Comment by sbcp1993** [comment]
Can anyone help me ????? Is there any way to get current DateTime in DotLiquid ???

**Comment by microalps** [comment]
Have you tried "date" instead of "Date" with a lowercase d? Please see https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Syntax-Compatibility#naming-convention

**Comment by sbcp1993** [comment]
It worked with "{{ 'Now' | Date:'yyyy-MM-ddTHH:mm:ss.fffffffZ' }}" this.

**Comment by microalps** [comment]
@DigitalSa1nt The try online portal is extremely outdated. If you have a current test case in .NET - please open a new ticket. Please be sure to specify if you are using c# or ruby casing.
