### ISSUE TITLE
Date filter results in wrong century with dates < 2000 SyntaxCompatibility.DotLiquid20 and system 2 digit year format 

### ISSUE THREAD

**Issue by didster** [dotliquid/dotliquid#464]
### Dotliquid version
2.2.548

### Expected behaviour

On systems with a 2 digit year format, when outputting the date 1st Jan 1949 via {{DOB|Date: "yyyy-MM-dd"}} expected result is 1949-01-01

### Actual behaviour

Actual result is 2049-01-01

### Steps to reproduce the Problem (you can add files)

Set windows default date format to one that has a 2 digit year, for example dd-MMM-yy
Create template with simple date out as above.
Input a year < 2000

This issue I think is caused by this code

`if (context.SyntaxCompatibilityLevel == SyntaxCompatibility.DotLiquid20)
    return DateLegacyParsing(input.ToString(), format);`

Which roundtrips the date to/from a string using the default ToString() on date which will use the system default date format, and thus since that is a 2 digit year, loose the century.  When it converts back to a DateTime in DateLegacyParsing, there is no century so it uses the current one of 20. 

Fix I guess is to ToString with ISO 8601 format or such like

Setting compatibility to  DotLiquid21 also fixes it as this code is then skipped

**Comment by microalps** [comment]
DateTimeOffset is not supported by DotLiquid20. We are not changing that behavior for backward compatibility reasons.

**Comment by didster** [comment]
Aha ok, understood.  Its worked just fine in the past so always assumed DTO was supported, I guess circumstantially as its round tripping to a string under the covers.  

At least I know, I'll close this and I'll work round it my end.

Thanks
