### ISSUE TITLE
Question: Parsing unnamed nested root arrays in JSON

### ISSUE THREAD

**Issue by SvenAelterman** [dotliquid/dotliquid#465]
### Dotliquid version
2.0.361 (as used by Azure Logic Apps)

### Steps to reproduce the Problem (you can add files)
Azure Logic App's SQL connector's Execute Query action returns a nested array without a name in JSON, like this:

```json
[
  [
    {
      "ProductID": 7000,
      "ProductName": "Some name"
    },
    {
      "ProductID": 7001,
      "ProductName": "Some other name"
    }
  ]
]
```

What would the dotLiquid template look like to iterate over those nested arrays (which have no name)?

**Comment by targetarchitecture** [comment]
@SvenAelterman  did you manage to get this working?

**Comment by SvenAelterman** [comment]
@targetarchitecture To test locally? No, I didn't, but I also haven't spent much time on it.

**Comment by daviburg** [comment]
Logic App uses a custom `IIndexable, ILiquidizable` class for JSon `JToken` 'drop'. While a fairly simple class to wrap the JSon in these interfaces understood by dotLiquid, it is not public code at this point.

**Comment by microalps** [comment]
This question relates to Azure Logic Apps and has been answered as best as possible. This issue can be continued with Microsoft Support if additional questions remain and any new information shared here. Closing this issue though.
