### ISSUE TITLE
New enum support is not backwards-compatible

### ISSUE THREAD

**Issue by vyrp** [dotliquid/dotliquid#468]
It seems that PR #449 broke backwards-compatibility regarding enums that are registered as safe type.

### Dotliquid version

Regression introduced in 2.2.547.

### Code snippet

```cs
Template.RegisterSafeType(typeof(E), value => value.ToString().ToLowerInvariant());
Console.WriteLine(Template.Parse("{{x}}").Render(Hash.FromAnonymousObject(new { x = E.A })));

enum E { A, B }
```

### Expected output

In version 2.2.544, the transformer function is respected (see [.NET Fiddle example](https://dotnetfiddle.net/OGj6eJ)):

```
a
```

### Actual behavior

In version 2.2.547, the transformer function is ignored (see [.NET Fiddle example](https://dotnetfiddle.net/ZPTlzd)):

```
A
```

**Comment by vyrp** [comment]
Would it be possible to fix this issue in the library? If not, is there a way to force DotLiquid to use the transformer function that I provided?

**Comment by microalps** [comment]
@vyrp I doubt many people are affected by this bug. Do you simply have a uppercase as the difference - which can easily be solved by changing your template to use a filter? Or is there something else going on not as easily solvable?

**Comment by microalps** [comment]
We are closing this issue as we have not gotten a response. Please reopen this issue when you update with more info.

**Comment by joergkrause** [comment]
> @vyrp wrote: I doubt many people are affected by this bug
I use this to translate Enum values by looking for an attribute and pull localized values. This is a scenario you can't replace by a simple filter, especially if the enum/DisplayAttribute stuff already exists and is used by other parts of a complex solution.
