### ISSUE TITLE
Includes failing on Ubuntu only

### ISSUE THREAD

**Issue by RussBaz** [dotliquid/dotliquid#471]
Hi. I am getting `Liquid error: Error - No such template 'inner'` on `{% include "inner" %}` but in Ubuntu only. It works normally in MacOS and Windows. I use the `LocalFileSystem` to set the correct content path.

I do not have an access to a proper Ubuntu machine right now and therefore I am struggling to debug this issue. Could you recommend anything?

### Dotliquid version
2.2.585 on .Net 6.0
### Steps to reproduce the Problem (you can add files)
I use GitHub Actions for automatic builds. You can check the failing Ubuntu build there.
Here is the repository link: https://github.com/RussBaz/WebFrame
To run the tests, clone the repo and do the following from its root folder (.Net 6.0 is required):
```
dotnet tool restore
dotnet paket install
dotnet restore
dotnet build
dotnet test
```

**Comment by RussBaz** [comment]
OK. I found out that the issue was due to a lack of capitalisation of my partial template name. Changing 'inner' to 'Inner' fixed an issue on every platform.

However, why is that inconsistent between platforms? Could someone please review my findings?

**Comment by microalps** [comment]
LocalFileSystem would be bound by the OS definition of a file system. Linux based OS are case-sensitive and you can have inner.liquid and Inner.liquid in the same folder.
