### ISSUE TITLE
Include doesn't allow nested template name with length of 1 symbol

### ISSUE THREAD

**Issue by nvborisenko** [dotliquid/dotliquid#472]
I want to include nested template via `{% include 'B' %}`, I have `_B.liquid` file near with my caller template.

**Error**: Liquid error: Error - Illegal template name 'B'

If I change `B` to `BB`, it starts to work.

**Comment by microalps** [comment]
seems like the bug is in EmbeddedFileSystem.cs and LocalFileSystem.cs - regex requires two or more characters. 
```c#
            if (templatePath == null || !Regex.IsMatch(templatePath, @"^[^.\/][a-zA-Z0-9_\/]+$"))
                throw new FileSystemException(Liquid.ResourceManager.GetString("LocalFileSystemIllegalTemplateNameException"), templatePath);
```
I see similar requirement in Ruby Liquid if I'm reading this correctly
``` rb
      raise FileSystemError, "Illegal template name '#{template_path}'" unless %r{\A[^./][a-zA-Z0-9_/]+\z}.match?(template_path)
```

**Comment by microalps** [comment]
I would suggest opening a bug report with Shopify Liquid project and see what that team says. Unfortunately, this regex is there from the initial import of Liquid into git so we have no idea why this was done. My two cents, it should probably be:

```
^(?!\/)[a-zA-Z0-9_\/]+(?<!\/)$
```

This solves for:
`abc/` is valid
`-abc` is valid but `a-bc` is not
`a` is not valid

**Comment by daviburg** [comment]
Looks like something we could fix whether Shopify fixes it or not. I don't see the point to prevent a one character file name, and it was likely not intentional in the original expression.

I'm not sure why the original expression has a negation of dot character start when dot character is not in the allowed range of characters that follow anyways.

**Comment by microalps** [comment]
I'm not sure either, but I'm sure it evolved prior to getting added to github, possibly allowing more characters originally. I don't understand the restriction against profile.edit.liquid as a filename either. I agree to fix, but we should hear out Ruby liquid devs with a issue report. @nvborisenko please report to Shopify Liquid and reference this issue.

**Comment by microalps** [comment]
@daviburg how do you suppose we fix this without potential to break existing code? My suggested regex would also fix a bug that allows any character in the first position (except . and /) unintentionally.

**Comment by daviburg** [comment]
If I understand this correctly, currently these templates are failed with the error message above. The fix will make these template work. I didn't see any scenario currently working which the fix will cause to fail. Is there any?

**Comment by daviburg** [comment]
Trying `/^[^.\/][a-zA-Z0-9_\/]+$/gm` vs `/^(?!\/)[a-zA-Z0-9_\/]+(?<!\/)$/gm` at https://regex101.com/

a would be now valid which is desired.
-abc and also abc/ would no longer valid, that is indeed a breaking change.

Per the Shopify thread there was an intend to prevent directory traversal for security reason. Security fixes would be one exception where a breaking change is acceptable. So maybe breaking abc/ is ok. Also abc/ is not a valid file name (on Windows at least).

But -abc is a valid file name. Why should '-' character be blocked, or for that matter any character not reserved for file name?

**Comment by microalps** [comment]
That's a good Q - but the allow list of characters in position 2+ is [a-zA-Z0-9_\/] but not hyphen. Same reason as the one-character limit - unknown origin from over a decade ago. I'm happy adding hyphen, but that's just an example (probably the most prominent). Also, maybe the prohibition of period (.) was to block hidden files in linux that use .htaccess or whatever, but as you noted dot is not allowed currently anyways.

Here is another suggestion - that will be a lot more forgiving.

^(?![\\\/\.])(?:[^<>:;,?\"*|\x00-\x1F\r\n\/\\]+|[\/\\](?!\.))+(?<!\/)$

My test suite:
```txt
\root\file
/root/file
folder/
root/.hidden
.hidden
../test

root/file.txt
root\file.txt
folder/file
folder\file
file
a
a/b
-abc
a-bc
```

**Comment by daviburg** [comment]
I had to tweak the escape characters to validate that, as `/^(?![\\\/.])(?:[^<>:;,?\\"*|\x00-\x1F\r\n\/\\]+|\/\\)+(?<!\/)$/gm`

but it appears to satisfy the suite of tests, i.e. all folder traversal and hidden files are blocked, but every other valid local file names are accepted. There I don't see a regression issue.

**Comment by microalps** [comment]
Sorry, pasted the wrong regex
```
^(?![\\\/\.])(?:[^<>:;,?\"*|\x00-\x1F\r\n\/\\]+|[\/\\](?!\.))+(?<!\/)$
```

and used the .net tester

**Comment by daviburg** [comment]
Which .net regex tester? There are many. This one: https://regextester.github.io/Xig_IVtcXFwvXC5dKSg_OltePD46Oyw_XCIqfFx4MDAtXHgxRlxyXG5cL1xcXSt8W1wvXFxdKD8hXC4pKSsoPzwhXC8pJA/XHJvb3RcZmlsZQovcm9vdC9maWxlCmZvbGRlci8Kcm9vdC8uaGlkZGVuCi5oaWRkZW4KLi4vdGVzdAoKcm9vdC9maWxlLnR4dApyb290XGZpbGUudHh0CmZvbGRlci9maWxlCmZvbGRlclxmaWxlCmZpbGUKYQphL2IKLWFiYwphLWJj/2

Tells me a number of folder traversal are passing:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/12040431/163252609-47ffb3d2-2269-4ec6-9ec3-9dcdd18bbefd.png">

**Comment by microalps** [comment]
regex101.com has a flavor choice
![image](https://user-images.githubusercontent.com/39801630/163253300-9521e92a-8b39-44ca-84fa-bb2b24181af8.png)

**Comment by microalps** [comment]
Oh, and subfolders are valid, just not breaking out of the directory with / or ..

**Comment by daviburg** [comment]
ah, ok, thanks for the clarifications.

Other test cases:

```
test/../../../../etc/shadow
c:\windows
/etc/passwd
http://other-site.com.br/other-page.htm/malicius-code.php
/var/www/html/admin/get.inc
```

We don't have any URL decoding of the values, right? So this is safe to pass:

`%2e%2e%2f`

Overall I think your latest regex is good.
