### ISSUE TITLE
Math filters do not convert strings to numbers

### ISSUE THREAD

**Issue by lalmstrom** [dotliquid/dotliquid#474]
### Dotliquid version
2.2.595

### Expected behavior
Input:
```liquid
{% assign s = '1' -%}
{{ s | plus: 1 }}
{{ s | minus: 1}}
{% assign idx = '0' | abs -%}
{% assign array = '1000,2000' | split: ',' -%}
{{ array[0] }}
{{ array[idx] }}
{% assign idx = idx | plus: 1 -%}
{{ array[1] }}
{{ array[idx] }}
```

Output:
```
2
0
1000
1000
2000
2000
```

### Actual behavior
Output:
```

11
Liquid error: Argument is not numeric (Parameter 'left')
1000

2000


```

**Comment by microalps** [comment]
Can you confirm you are using DotLiquid 2.1 syntax (not just version) or higher?

See #419 Issue #1 and https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Syntax-Compatibility#strict-liquid-syntax-21

**Comment by microalps** [comment]
I'm not getting the same result. 

> 
> 2
> 1000
> 
> 2000
> 

The issue seems to be with your abs filter which doesn't seem to return an integer. Or possibly accessing array by string instead of integer. Not sure either of these are allowed in Ruby Liquid.

**Comment by lalmstrom** [comment]
> I'm not getting the same result.
> 
> > 2
> > 0
> > 1000
> > 2000
> 
> The issue seems to be with your abs filter which doesn't seem to return an integer (code indicates it returns a double). Or possibly accessing array by string/double instead of integer. Not sure either of these are allowed in Ruby Liquid.

What DotLiquid version are you using to get a working minus/plus filter and which Syntax compatibility?
I have not tried the above liquid template with official ruby implementation, but with liquid-python and this online editor:
https://geekplayers.com/run-liquild-online.html

**Comment by microalps** [comment]
@lalmstrom working to get the build pushed to nuget, apologies for the delay. Ticket was closed automatically.

**Comment by lalmstrom** [comment]
> @lalmstrom working to get the build pushed to nuget, apologies for the delay. Ticket was closed automatically.

Really prompt reply/work, if you ask me. I did not expect it to be fixed this quickly. When is the nuget expected to be pushed?

**Comment by lalmstrom** [comment]
@microalps What version of DotLiquid is running on the live editor? 
http://dotliquidmarkup.org/try-online

I get this result:
![image](https://user-images.githubusercontent.com/40788675/159882426-e84bdbec-8b6d-43b9-8878-e927ec6d1746.png)

**Comment by microalps** [comment]
Website is running very old version, I'm not certain myself. It's got to be 4+ years outdated as the site integration with github is at least that old. Tim Jones pushed new API key so you should have new build now.

**Comment by lalmstrom** [comment]
@microalps I got a new build. The `abs` variant works, but not `{{ s | plus: 1 }}` and `{{ s | minus: 1}}`. Did you need to "configure" DotLiquid to get that to work?

**Comment by lalmstrom** [comment]
@microalps Found the issue. I had to dig through the DotLiquid code to find it. I did not set `DefaultSyntaxCompatibilityLevel`, I only used `Template.Parse` with `SyntaxCompatibiltyLevel` as argument. My expectation was that the `DefaultSyntaxCompatibilityLevel` was only used when `Template.Parse` was used without a `SyntaxCompatibiltyLevel` argument. The `Context` is only initialized with `DefaultSyntaxCompatibilityLevel`, thus does not care about the `Template.Parse` argument. Is that a bug?

**Comment by microalps** [comment]
These are two separate methods in DotLiquid - Parse and Render. Although you need to run both for the end result, they are static methods that do not share their Syntax versioning. You would need to explicitly specify DotLiquid22 to both methods if you want to leave the default as is. Render is the phase where filters are executed and variables computed.

You many want to reread https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Syntax-Compatibility#strict-liquid-syntax-21 for further information about specifying the DotLiquid Syntax Version.

**Comment by lalmstrom** [comment]
@microalps Reread it. I completely missed the `RenderParameters.SyntaxCompatibilityLevel`. However, the example is incorrect as it only sets the SyntaxCompatbilityLevel for `Render()` and not `Parse()`. 

To me it feels like an odd API design choice to require SyntaxCompatibliityLevel in two functions, especially as `Parse()` returns a Template object which one use to call `Render()`. I expected that the SyntaxCompatiblityLevel  passed to `Parse()` would be stored in the Template object returned. That is a discussion for another PR, though.

It all works as expected to me now. Thank you!
