### ISSUE TITLE
Why Hash.FromDictionary uses generic dictionary rather than Hash as nested properties in v2.2.508?

### ISSUE THREAD

**Issue by QuanWanxx** [dotliquid/dotliquid#476]
Hi, we are using Dotliquid in our product, recently we'd like to upgrade the Dotliquid version to v2.2.508 to seek for latest features.

I found in this [commit](https://github.com/dotliquid/dotliquid/commit/32950d503cf48baf2dd72e73dbb3480681018ea6),. ```Hash.FromDictionary``` method uses generic ```Dictionary``` rather than raw ```Hash``` objects as nested properties. 

```
* Removed recursive FromDictionary call.
Replaced nested Hash objects in for/cycle tags with generic Dictionary

```

I want to know why we have this change, and is there any recommended way to still create a nested ```Hash``` object from a ```Dictionary```?

### Dotliquid version
v2.2.508

### Expected behavior
Create a nested ```Hash``` object from a ```Dictionary```

### Actual behavior
Create a ```Hash``` object nested with ```Dictionary``` from a ```Dictionary```

### Steps to reproduce the Problem (you can add files)

**Comment by microalps** [comment]
Can you provide a sample code that demonstrates the issue with previously working code? Should be 25 lines or less, not your entire app.

**Comment by QuanWanxx** [comment]
Hi @microalps ,

The below example code will print ```System.Collections.Generic.Dictionary`2[System.String,System.Object]``` if DotLiquid version larger than **2.1.469**, and will print ```DotLiquid.Hash``` if DotLiquid version is higher.

```Csharp
var innerDictionary = new Dictionary<string, object>
{
	{ "InnerKey", 123 },
};

var outerDictionary = new Dictionary<string, object>
{
	{ "OuterKey", innerDictionary },
};

var dotLiquidHash = Hash.FromDictionary(outerDictionary);

Console.WriteLine(dotLiquidHash["OuterKey"].GetType());

// "System.Collections.Generic.Dictionary`2[System.String,System.Object]" if DotLiquid > 2.1.469
// "DotLiquid.Hash" in other 
```

I want to know why we have this change? Any recommended way to still do previous ```FromDictionary```?
We have already widely used ```Hash``` in our project, so I'd like to know if there is any concern for this change.

**Comment by microalps** [comment]
Example doesn't show a template that fails that previously did. True, the type is different but it works internally either way.

**Comment by QuanWanxx** [comment]
Yeah, there's no fails that previously did. This is just a question.

We have widely used ```Hash``` in our project, so we may need to update many interfaces which take ```Hash``` as the input or return ```Hash``` object, because the inner elements from new ```Hash.FromDictionary``` are changes.

I'm trying to understand why DotLiquid do not convert all nested elements to ```Hash``` in ```Hash.FromDictionary``` or ```Hash.FromAnonymousObject```(when includeBaseClassProperties is True).
Are those designs just for performance? Or there are any other concerns?

**Comment by microalps** [comment]
I think we found it to be a useless conversion, and thus a performance hit, as dictionaries are supported internally within the DotLiquid framework.
