### ISSUE TITLE
Documentation: Render with filters

### ISSUE THREAD

**Issue by pekspro** [dotliquid/dotliquid#480]
On this page: https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Developers it says that filters could be passed to the `Render` method. Is this correct? I do not find any overload like that.

**Comment by microalps** [comment]
See https://github.com/dotliquid/dotliquid/blob/master/src/DotLiquid.Tests/Helper.cs#L61 - it is passed as a renderparameter object. Thanks for the catch!

**Comment by pekspro** [comment]
Thank @microalps. I have updated the Wiki :-)

**Comment by microalps** [comment]
@pekspro can you commit changes to the DotLiquid website "learn" page as well? https://github.com/dotliquid/dotliquid/tree/master/src/DotLiquid.Website/Views/Docs

**Comment by pekspro** [comment]
@microalps, sure! I will give it a try in a few days
