### ISSUE TITLE
FromAnonymousObject(this, true) does not support the superclass of the superclass

### ISSUE THREAD

**Issue by schlechtOptimiziert** [dotliquid/dotliquid#499]
# General Info
- based on closed issue #221 

# Explained issue
Hash.FromAnonymousObject(this, true) only enables you to access the first superclass. The superclass of the superclass can't be accessed.
I made an example of it and send it to the Gitter chat. Exact time of sending it: Jul 12 10:11 (for you to find it easily)

## Workaround
I am aware of the workaround explained in the referenced issue but it is very annoying to implement. You would literally convert all your objects into nestled Dictionaries.

### example
```
void Main()
{
    var template = "{% for classe in classes %} {{classe.string2}} {{classe.string3}} {{classe.string4}} {% endfor %}";


    var temp = Template.Parse(template).Render(Hash.FromAnonymousObject(new class1(), true));

    Console.WriteLine(temp);
}

class class1 : ILiquidizable
{
    public class2[] classes { get; set; } = new class2[] { new class2() };

    public object ToLiquid()
    {
        return Hash.FromAnonymousObject(this, true);
    }
}

class class2 : class3, ILiquidizable
{
    public string string2 { get; set; } = "foo";

    public object ToLiquid()
    {
        return Hash.FromAnonymousObject(this, true);
    }
}

class class3 : class4
{
    public string string3 { get; set; } = "bar";
}

class class4
{
    public string string4 { get; set; } = "foolbar";
}
```

Wanted outcome: "foo bar foolbar"
Outcome: "foo bar"

**Comment by microalps** [comment]
Resolved by #519
