### ISSUE TITLE
Pager Support?

### ISSUE THREAD

**Issue by HybridSolutions** [dotliquid/dotliquid#502]
There's been some updates to this awesome project but noticed that a very important upgrade from one of the users has not been included in the base source. This commit added paging features to dotliquid, so why has this been left out?

https://github.com/dotliquid/dotliquid/pull/78/commits

Thank you!

**Comment by microalps** [comment]
The PR you refer to is labeled as rebase-me and has not been rebased. I will also note that the purpose of this project is to mimic the Ruby Liquid implementation, and pager is not a standard feature there as far as I see. If there is interest in this and a willing contributor, please reopen this issue.
