### ISSUE TITLE
Template Render Performance Issues

### ISSUE THREAD

**Issue by arielbvargas** [dotliquid/dotliquid#505]
### Dotliquid version: 
2.2.656

### Expected behavior: 
Rendering a template of an e-commerce product catalog page is taking 650ms in the development environment and more than 3.5 segs in production.

### Actual behavior
Slow rendering time in a 24-procs dedicated server.

Did anybody had similar issues?

**Comment by HybridSolutions** [comment]
That is very vague. Is your template loading many products? In my own templates never felt such issues.

**Comment by microalps** [comment]
@arielbvargas can you add any more information about the issue? How many products would be a useful starting point. An actual simplified test would be super helpful. If we don't hear back in 7 days, we will need to close this issue.
