### ISSUE TITLE
How to get the list of variables used in a liquid template?

### ISSUE THREAD

**Issue by AnushaKaraka** [dotliquid/dotliquid#530]
### Actual behavior: Using the following code, I am getting a list of variables used in a template but that are only at root level. I wanted to get the variables included in all of the template including inside If, Case, For and Assign tags. When I debug the code, I can see the variables in various properties for each of these tags, but all those properties are Private, hence inaccessible. Is there any easy way to retrieve all the DotLiquid variables in a give template?
`var variables = _template.Root.NodeList
                .Where(x => x is Variable)
                .OfType<Variable>();`

**Comment by microalps** [comment]
Why would this be something in the interest of the project? You can't programmatically do anything like that in, say, Visual Studio, let alone in runtime. It seems like you are approaching a problem with an incorrect approach. We will keep this open for further discussion for a week.

**Comment by AnushaKaraka** [comment]
There is a requirement for us where I need to parse all the dotliquid variables from a template and replace them with new properties to re-render the template. Something similar to this,

https://stackoverflow.com/questions/29696259/how-to-get-list-of-variables-referenced-in-a-liquid-template

https://github.com/Shopify/liquid/issues/685#issuecomment-471499796

**Comment by microalps** [comment]
This would not be a function of DotLiquid - it seems like you want a tool to generate new templates which this is not. While it certainly may overlap with exposed variables, it would not be a supported use of DotLiquid.
