### ISSUE TITLE
Dotliquid not parsing object array in liquid template

### ISSUE THREAD

**Issue by furqanms** [dotliquid/dotliquid#534]
### Expected behavior
[
	"Apple - $1.99",
	"Banana - $0.99",
	"Orange - $1.49",
]

### Actual behavior
[
]

### Steps to reproduce the Problem (you can add files)
Liquid Template : test.liquid 

```
{% assign fruits = [
  {"name": "Apple", "price": 1.99},
  {"name": "Banana", "price": 0.99},
  {"name": "Orange", "price": 1.49}
] %}

[
{% for fruit in fruits %}
  "{{ fruit.name }} - ${{ fruit.price }}",
{% endfor %}
]
```

Is there any way to define json array in liquid and populate in liquid to produce a result ?

Thanks in advance!

**Comment by microalps** [comment]
Seems like this is a non-supported template in any flavor of liquid. I tested against https://jumpseller.co.uk/support/liquid-sandbox/ without success. I believe assign is for simple primitive values only, although it can be used with custom filters to convert a json string to a .NET object. DotLiquid doesn't include any support for JSON encoding/decoding and has no dependencies on Newtonsoft.Json or System.Text.Json libraries.
