### ISSUE TITLE
Empty string / null check not working

### ISSUE THREAD

**Issue by thinkOfaNumber** [dotliquid/dotliquid#537]
A simple test for null or empty is not working. I've verified the behaviour with LiquidJS and an identical liquid file and it works fine.

```
{% assign ItemExists = content.existing != null and content.existing.UID != null and content.existing.UID != "" -%}
{{ content.existing.Control }}
{% if ItemExists -%}
Test FAILED!
{% else -%}
Test PASSED!
{% endif -%}
```

Given the anonymous input:
```
new {
    content = new
    {
        existing = new
        {
            Control = "Control passed",
            UID = "",
        }
    }
}
```
the `Test FAILED!` text should not be printed, but it is.

### Dotliquid version
2.2.692

### Expected behavior
Given the above object, the `ItemExists` should be assigned a false value.

### Actual behavior
`ItemExists` is true

### Steps to reproduce the Problem (you can add files)
Program.cs for .NET 6 console app:
```
using DotLiquid;

var file = File.ReadAllText("Test.liquid");
Template template = Template.Parse(file);
var result = template.Render(Hash.FromAnonymousObject(new {
    content = new
    {
        existing = new
        {
            Control = "Control passed",
            UID = "",
        }
    }
}));

Console.WriteLine(result);
```

Liquid template shown above.

**Comment by thinkOfaNumber** [comment]
I can't find any tests for "or" operators in the tests folder... Did I miss it somewhere?

It appears like the parser is either broken or doesn't support chained operators, for example this:

```
{% assign test = "asdf" -%}
{% assign isNullOrWhitespace = test == null or test == empty %}
```

line 2. is assigning the value of `test` to `isNullOrWhitespace`, instead of evaluating the `==` first. i.e. `isNullOrWhitespace` now has the value "asdf"!

**Comment by thinkOfaNumber** [comment]
Someone proposed [this solution on stackoverflow](https://stackoverflow.com/a/77611788/1089267). If you change test between "asdf" and "" it will print the correct response.

```
{% assign test = "asdf" %}
{% assign isItemExists = test | default: nil | unless: empty %}
{% if isItemExists %}
  The string is not empty and not null. 
  Value: {{ test }}
{% else %}
  The string is empty or null.
{% endif %}
```

**Comment by thinkOfaNumber** [comment]
Is DotLiquid still maintained?

Also, I'm assuming as I can't find it explicitly stated, this lib is used in Azure Logic apps for the liquid template action, right?

**Comment by azharmunir-ms** [comment]
Yes, Azure Logic Apps are using this library
https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform?tabs=consumption#liquid-template-considerations

**Comment by microalps** [comment]
> A simple test for null or empty is not working. 
Then you proceed to detail a template that assigns, not test. If I am understanding you correctly, you want the assign to behave similar to the if tag. Do you have a ruby test (see other tickets for samples on replit) that indicates that assigns is supposed to work that way? https://shopify.dev/docs/api/liquid/tags/assign doesn't have such example nor any tests in https://github.com/Shopify/liquid/blob/master/test/integration/assign_test.rb

> I can't find any tests for "or" operators in the tests folder... Did I miss it somewhere?
We have TestIfOr and TestIfOrWithOperators, which is where conditions are implemented.

**Comment by thinkOfaNumber** [comment]
> > A simple test for null or empty is not working.
> 
> Then you proceed to detail a template that assigns, not test.

Well it does both assign and a boolean operator. The assignment is to capture the result somewhere to do something with it. The behaviour I'm interested in is the boolean tests (and, or, ...). An order of operation for an assignment operator should return the RHS of the assignment as a whole. Perhaps it is an issue with the assignment operator and I haven't done enough samples - I'll try it out.

I have verified that Shopify liquid works as I expect, and different to dotliquid.

> If I am understanding you correctly, you want the assign to behave similar to the if tag. Do you have a ruby test (see other tickets for samples on replit) that indicates that assigns is supposed to work that way? https://shopify.dev/docs/api/liquid/tags/assign doesn't have such example nor any tests in https://github.com/Shopify/liquid/blob/master/test/integration/assign_test.rb

Maybe the assignment is a red herring - I used some other implementations of liquid to verify that it should work as I expect, so maybe I should do that again without an assignment operator. I'll have a look at ruby and should be able to create something for you...

> > I can't find any tests for "or" operators in the tests folder... Did I miss it somewhere?
> 
> We have TestIfOr and TestIfOrWithOperators, which is where conditions are implemented.

Ah found them, thanks, I'll extend that and let you know how it goes... It will take me a day or two to get enough time but should be able to figure out exactly where the issues is.

**Comment by thinkOfaNumber** [comment]
I setup some tests on replit, and after going around in circles I've found the issue is reproducable there, but only when the nil/null check is at the beginning of an expression, and not at the end. e.g. this:

`assign x = a != nil and b == true` will assign the string value of a to the variable x, and essentially discard the rest. However this:

`assign x = b == true and a != nil` will correctly evaluate the and operator and two boolean expressions, and assign a boolean value to x.

The _and_ operator **should be** commutative, however it looks like various versions of liquid get this wrong, and if dotliquid's goal is to emulate shopify liquid - bugs and all - then your behaviour is correct.

Here's the replit tests:
https://replit.com/@thinkofanumber/LiquidBooleanNullCheck#main.rb
and results:
![image](https://github.com/dotliquid/dotliquid/assets/5110983/a446a31f-3dac-4fe1-8067-60b51f2f99e8)

And here's the same tests converted to C# using DotLiquid, as you can see they both fail on the same `test_assign_bool_with_stringnil_at_start`:
![image](https://github.com/dotliquid/dotliquid/assets/5110983/561a7015-727c-47c4-bff0-755ae5643763)

If this is "not a bug" can this be turned into a documentation update? It's unexpected behaviour and took me a long time to figure out.

**Comment by microalps** [comment]
@thinkOfaNumber This is some great research and some pro ruby chops. Happy to finally see a good test replit to mimic for the future! Here is how I suggest moving forward:

1. Open a ticket on Shopify Liquid github and reference this ticket. Let's hear their thoughts.
2. Share your c# tests regarding assign (I think the others are surely covered) so I can research further.

**Comment by microalps** [comment]
@thinkOfaNumber  did you end up creating a ticket on Shopify's github?

**Comment by microalps** [comment]
Closing this issue as this library is intended to match the upstream Ruby implementation and it seemingly does based on the replit.
