### ISSUE TITLE
Working with Dictionary object when key is not KNOWN

### ISSUE THREAD

**Issue by smevans521** [dotliquid/dotliquid#54]
I have a basic .NET Dictionary (Dictionary<string,string>). In my ToLiquid method I do indeed serialize/expose the Dictionary object. My question is how can I ITERATE over the keys in a liquid template just as you would do in regular .NET? It seems as though you MUST know the actual key in order to access the value in the liquid template.

I understand that you could access the value in the liquid template like such

item.dictionary["myKey"]

However I don't know the actual key, so I would prefer to use the "for" construct in DotLiquid to iterate over the keys in order to get the various values. Since the "for" construct works on collections and Dictionary is a collection I thought this could be done somehow but all permutations that I have tried have failed.

Any help would greatly be appreciated.

**Comment by scootabug** [comment]
@gregmac @tgjones 

Hey guys.  Well 6 years later and I'm trying to get _both the key and the value_ from a Dictionary<string,string>.  I don't know what the key is, clearly. :smile:

This is a sample of the JSON I am trying to render:

`{ "success": true, "timestamp": "2018-02-12T03:15:36+00:00", "response_code": 200, "data": { "visitors": [{ "id": 1028285, "first_seen": "2018-01-03T05:24:58+00:00", "last_seen": "2018-01-03T05:24:58+00:00", "visits": "1", "form_data": [{ "Country": "UK" }, { "Favourite Drink": "Water" } ], "terms_signed": [], "unsubscribed": false }] }}`

[Easier to see the JSON here](https://jsoneditoronline.org/?id=ff32257c292b98c9eedf4f4d442025de)  on JSON Editor Online.

How do I get the key and value from the form_data?  I'm trying everything I can think of, but alas, no joy:

`{% for visitor in data.visitors %}
{% if visitor.form_data.size > 0 %}
{% for fd in visitor.form_data %}
visitor.id: "{{visitor.id}}",
fd: "{{fd}}",
fd.key: "{{fd.key}}",
fd.value: "{{fd.value}}"
fd[0]: "{{fd[0]}}",
fd[1]: "{{fd[1]}}",
fd.dictionary: "{{fd.dictionary}}",
{% for kv in fd.dictionary %}
	Key is {{kv.Key}}, value is {{kv.Value}};
{% endfor %}
{% endfor %}{% endif %}{% endfor %}`

Closest I get above: {{fd}} returns me [Country, UK] and [Favourite Drink, Water].  

Any tips would be very helpful!

Thanks,
Scott
