### ISSUE TITLE
base64_encode / base64_decode filters

### ISSUE THREAD

**Issue by mikeclayton** [dotliquid/dotliquid#542]
### Dotliquid version
2.2.692

### Expected behavior
Using "base64_encode" or "base64_decode" as filters should convert the value as appropriate:

**[base64_encode](https://shopify.dev/docs/api/liquid/filters/base64_encode)**
```
{{ some_value | base64_encode }}
```

**[base64_deecode](https://shopify.dev/docs/api/liquid/filters/base64_decode)**
```
{{ some_value | base64_decode }}
```

### Actual behavior
No filter is applied and the existing input value is returned as the output.

### Steps to reproduce the Problem (you can add files)

**Comment by microalps** [comment]
These filters are not standard filters or documented in the wiki extensions. Looking at Shopify this was added in the last few years in [v5.0.2 ](https://github.com/Shopify/liquid/blob/017c1b5e836fb25e8f9bec2531a436f243b8cad6/History.md). Happy to review a PR that implements them.

**Comment by microalps** [comment]
I find that #511 included this. You might want to use that as a starting point and take ownership of the PR.
