### ISSUE TITLE
[Question] Variable.Render spends most of the time in ToList operation

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotliquid/dotliquid#543]
### Dotliquid version
Latest

Hello, DotLiquid owners, first of all, thanks a lot for developing and maitaining this library which saves a lot of time for other people in the industry!

My team at Microsoft uses this library and when I was looking into the performance of the application that relies on that, I've found some cases that potentially might be improved.

Here is an exampe:
![image](https://github.com/dotliquid/dotliquid/assets/726448/b76f8fcf-cdf1-4995-8f34-884437bbe3c4)

By looking into the code I can see two candidates: `Filters.ToList()` and `filter.Arguments.Select(a => context[a]).ToList()`.

I have two questions:

1. How important the `Filters.ToList()` here? Do we afraid that `Filters` would be changed in the process of enumeration and that was could cause an issue?
2. How open are you for making safe performance improvements in the code?
I've been doing quite a bit of performance work (see [my twitter](https://twitter.com/STeplyakov)) and would be happy to contribute. For instance, normally, pooling lists and dictionaries that I can see are allocated quite a lot, could be a huge source of improvements.
Of course, if you feel that the community would benefit from it, I'll create PRs with evidence of the perf imrovements with benchmarks results, profiling results and the end-to-end impact.

Once again, really appreciate the work, the community put into this project!

**Comment by SergeyTeplyakov** [comment]
Btw, my analysis of what exactly takes the most time is incorrect, but the second question is the most relevant one. Would you be interested in perf contributions or you think that the perf is ok for most of the customers and you won't risk regressions because of that?

**Comment by microalps** [comment]
First, any contribution that would improve the performance with non-breaking changes would be fine by me. 

I believe @daviburg is also at Microsoft - I'm sure you two can connect directly. He is a project owner and can approve your changes same as myself. I haven't heard from him lately though.

**Comment by SergeyTeplyakov** [comment]
Thanks for the answer! I'll keep in touch with devidburg.
