### ISSUE TITLE
Unable to compare Guid type in the template

### ISSUE THREAD

**Issue by Vijay-Kumar-intelliflo** [dotliquid/dotliquid#544]
### Dotliquid version
version 2.2.692
### Expected behavior
I should be able to compare two Guid values in the template.
### Actual behavior
I am unable to compare Guid in the template , equal operator returning null
### Steps to reproduce the Problem (you can add files)
Can reproduce by adding this test case to TemplateTests.cs, which is failing 
```  
 [Test]
   public void TestGuidComparison()
   {
       string template = "{% if {{context}} == '00000000-0000-0000-0000-000000000000' %}hi tobi{% endif %}";

       Assert.AreEqual("hi tobi", Template.Parse(template, SyntaxCompatibility.DotLiquid22).Render(Hash.FromAnonymousObject(new { context = default(Guid) })));
   }
```

**Comment by microalps** [comment]
> I should be able to compare two Guid values in the template.

Is there any reference that this is supported in Ruby Liquid? Such as a test on replit?

**Comment by Vijay-Kumar-intelliflo** [comment]
i was unable to find any references in Ruby liquid, as we can't have default GUID in Ruby as we do in .Net 

To get around the issue i used nullable GUID and compare it with Nil operator
