### ISSUE TITLE
Operator precedence and braces in conditions

### ISSUE THREAD

**Issue by Pixelrise** [dotliquid/dotliquid#92]
Hey Tim,

first of all, great job with this lightweight and powerfull template engine in .NET!

Unfortunatelly I have got some trouble with some conditions.
Thus it is not possible to use braces in conditions like {% if (var1 or var2) and var3 %} (see bottom example) I tried to use the disjunctive normal form, because I thought that the AND operator has a higher precedence as the OR operator.
But the result of {% if var1 and var3 or var2 and var3  -%} is false, if I use the following assignments:
{% assign var1 = false %}
{% assign var2 = true %}
{% assign var3 = true %}  

Btw: {% if (var1 or var2) and var3 %} would give me the correct result "true". But if I have the following assigments, the result is wrongly still "true".
{% assign var1 = true %}
{% assign var2 = true %} 
{% assign var3 = false %}  

I cannot explain this behaviour.
Is it possible to use more than two conditions at all? 
Please help me. :-)

Thank you in advance

Greets,
Alex

**Comment by Flimm** [comment]
+1

**Comment by haf** [comment]
Would be a great PR!

**Comment by Flimm** [comment]
I'm confused. Is this closed because it has been fixed?

**Comment by haf** [comment]
No, it's closed because there was just so many stale issues and PRs in the list that things people wanted resolved and were getting drowned in the noise.

Do you want this bug fixed?

**Comment by Flimm** [comment]
No worries. I just wanted to be clear. When I run into bugs, I often find GitHub issues describing the problem, closed with no clear indication as to why, and it's quite frustrating. I just wanted to clarify why this was closed.

**Comment by haf** [comment]
Alright. I'm leaving this issue here until further notice. I'm trying to whip some structure into releases of this repository :). Thanks @Flimm for being understanding.
