### ISSUE TITLE
Allow non-global template configuration

### ISSUE THREAD

**Issue by rdumont** [dotliquid/dotliquid#93]
This proposal is intended to provide a way to use multiple rendering configurations in an application, so that you don't have to use the global tag/filter/safe type/naming convention/file system configuration.

Currently template configuration is done as follows:

```csharp
Template.RegisterTag<MyTag>("my");
Template.NamingConvention = new CSharpNamingConvention();
// etc.

var template = Template.Parse("some template text");
var result = template.Render();
```

My intention is to allow the following syntax, while keeping the former for compatibility and simplicity for those who only need global registration.

```csharp
var config = new LiquidConfiguration();
config.RegisterTag<MyTag>("my");
config.NamingConvention = new CSharpNamingConvention();
// etc.

var template = Template.Parse("some template text", config);
var result = template.Render();
```

I also thing it would be interesting to provide a more fluent configuration, such as:

```csharp
var config = new LiquidConfiguration()
    .RegisterTag<MyTag>("my")
    .SetNamingConvention(new CSharpNamingConvention());
```

Any ideas? I intend on sending a pull request ASAP.

**Comment by haf** [comment]
The solution to this is to rebase https://github.com/dotliquid/dotliquid/pull/94 so that I can merge it.
